
package br.ufc.safe.sample.stubs.server.tsk;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerServiceTsk", targetNamespace = "http://server.service.sample.safe.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerServiceTsk {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "request", targetNamespace = "http://server.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.server.tsk.Request")
    @ResponseWrapper(localName = "requestResponse", targetNamespace = "http://server.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.server.tsk.RequestResponse")
    @Action(input = "http://server.service.sample.safe.ufc.br/ServerServiceTsk/requestRequest", output = "http://server.service.sample.safe.ufc.br/ServerServiceTsk/requestResponse")
    public void request();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "get", targetNamespace = "http://server.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.server.tsk.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://server.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.server.tsk.GetResponse")
    @Action(input = "http://server.service.sample.safe.ufc.br/ServerServiceTsk/getRequest", output = "http://server.service.sample.safe.ufc.br/ServerServiceTsk/getResponse")
    public void get();

}
