
package br.ufc.safe.sample.stubs.server.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerServiceTskService", targetNamespace = "http://server.service.sample.safe.ufc.br/", wsdlLocation = "http://localhost:10007/server-task?wsdl")
public class ServerServiceTskService
    extends Service
{

    private final static URL SERVERSERVICETSKSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERSERVICETSKSERVICE_EXCEPTION;
    private final static QName SERVERSERVICETSKSERVICE_QNAME = new QName("http://server.service.sample.safe.ufc.br/", "ServerServiceTskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10007/server-task?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERSERVICETSKSERVICE_WSDL_LOCATION = url;
        SERVERSERVICETSKSERVICE_EXCEPTION = e;
    }

    public ServerServiceTskService() {
        super(__getWsdlLocation(), SERVERSERVICETSKSERVICE_QNAME);
    }

    public ServerServiceTskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERSERVICETSKSERVICE_QNAME, features);
    }

    public ServerServiceTskService(URL wsdlLocation) {
        super(wsdlLocation, SERVERSERVICETSKSERVICE_QNAME);
    }

    public ServerServiceTskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERSERVICETSKSERVICE_QNAME, features);
    }

    public ServerServiceTskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerServiceTskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerServiceTsk
     */
    @WebEndpoint(name = "ServerServiceTskPort")
    public ServerServiceTsk getServerServiceTskPort() {
        return super.getPort(new QName("http://server.service.sample.safe.ufc.br/", "ServerServiceTskPort"), ServerServiceTsk.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerServiceTsk
     */
    @WebEndpoint(name = "ServerServiceTskPort")
    public ServerServiceTsk getServerServiceTskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.service.sample.safe.ufc.br/", "ServerServiceTskPort"), ServerServiceTsk.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERSERVICETSKSERVICE_EXCEPTION!= null) {
            throw SERVERSERVICETSKSERVICE_EXCEPTION;
        }
        return SERVERSERVICETSKSERVICE_WSDL_LOCATION;
    }

}
