
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.go;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSIClientProducerGoPort", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSIClientProducerGoPort {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.go.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.go.GoResponse")
    @Action(input = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/WSIClientProducerGoPort/goRequest", output = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/WSIClientProducerGoPort/goResponse")
    public void go();

}
