
package br.ufc.safe.sample.stubs.queue.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QueueServiceTskService", targetNamespace = "http://queue.service.sample.safe.ufc.br/", wsdlLocation = "http://localhost:10006/queue-task?wsdl")
public class QueueServiceTskService
    extends Service
{

    private final static URL QUEUESERVICETSKSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUEUESERVICETSKSERVICE_EXCEPTION;
    private final static QName QUEUESERVICETSKSERVICE_QNAME = new QName("http://queue.service.sample.safe.ufc.br/", "QueueServiceTskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10006/queue-task?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUEUESERVICETSKSERVICE_WSDL_LOCATION = url;
        QUEUESERVICETSKSERVICE_EXCEPTION = e;
    }

    public QueueServiceTskService() {
        super(__getWsdlLocation(), QUEUESERVICETSKSERVICE_QNAME);
    }

    public QueueServiceTskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUEUESERVICETSKSERVICE_QNAME, features);
    }

    public QueueServiceTskService(URL wsdlLocation) {
        super(wsdlLocation, QUEUESERVICETSKSERVICE_QNAME);
    }

    public QueueServiceTskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUEUESERVICETSKSERVICE_QNAME, features);
    }

    public QueueServiceTskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueueServiceTskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IQueueServiceTsk
     */
    @WebEndpoint(name = "QueueServiceTskPort")
    public IQueueServiceTsk getQueueServiceTskPort() {
        return super.getPort(new QName("http://queue.service.sample.safe.ufc.br/", "QueueServiceTskPort"), IQueueServiceTsk.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IQueueServiceTsk
     */
    @WebEndpoint(name = "QueueServiceTskPort")
    public IQueueServiceTsk getQueueServiceTskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://queue.service.sample.safe.ufc.br/", "QueueServiceTskPort"), IQueueServiceTsk.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUEUESERVICETSKSERVICE_EXCEPTION!= null) {
            throw QUEUESERVICETSKSERVICE_EXCEPTION;
        }
        return QUEUESERVICETSKSERVICE_WSDL_LOCATION;
    }

}
