
package br.ufc.m101.stubs.mfitexec.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MFitExecEnvPortImplService", targetNamespace = "http://mfitexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11408/mfitexec-env?wsdl")
public class MFitExecEnvPortImplService
    extends Service
{

    private final static URL MFITEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MFITEXECENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MFITEXECENVPORTIMPLSERVICE_QNAME = new QName("http://mfitexec.component.m101.ufc.br/", "MFitExecEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11408/mfitexec-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MFITEXECENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MFITEXECENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MFitExecEnvPortImplService() {
        super(__getWsdlLocation(), MFITEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MFitExecEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MFITEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MFitExecEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MFITEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MFitExecEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MFITEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MFitExecEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MFitExecEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MFitExecEnvPort
     */
    @WebEndpoint(name = "MFitExecEnvPortImplPort")
    public MFitExecEnvPort getMFitExecEnvPortImplPort() {
        return super.getPort(new QName("http://mfitexec.component.m101.ufc.br/", "MFitExecEnvPortImplPort"), MFitExecEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MFitExecEnvPort
     */
    @WebEndpoint(name = "MFitExecEnvPortImplPort")
    public MFitExecEnvPort getMFitExecEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mfitexec.component.m101.ufc.br/", "MFitExecEnvPortImplPort"), MFitExecEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MFITEXECENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MFITEXECENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MFITEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
