
package br.montage.stubs.mBgExec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mBgExec", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMBgExec {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mBgExec/goRequest", output = "http://be.montage.ufc.br/I_mBgExec/goResponse")
    public void go();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUsesOut", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetDirPortUsesOut")
    @ResponseWrapper(localName = "setDirPortUsesOutResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetDirPortUsesOutResponse")
    @Action(input = "http://be.montage.ufc.br/I_mBgExec/setDirPortUsesOutRequest", output = "http://be.montage.ufc.br/I_mBgExec/setDirPortUsesOutResponse")
    public void setDirPortUsesOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblPortUsesA", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetTblPortUsesA")
    @ResponseWrapper(localName = "setTblPortUsesAResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetTblPortUsesAResponse")
    @Action(input = "http://be.montage.ufc.br/I_mBgExec/setTblPortUsesARequest", output = "http://be.montage.ufc.br/I_mBgExec/setTblPortUsesAResponse")
    public void setTblPortUsesA(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblPortUsesB", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetTblPortUsesB")
    @ResponseWrapper(localName = "setTblPortUsesBResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetTblPortUsesBResponse")
    @Action(input = "http://be.montage.ufc.br/I_mBgExec/setTblPortUsesBRequest", output = "http://be.montage.ufc.br/I_mBgExec/setTblPortUsesBResponse")
    public void setTblPortUsesB(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUsesIn", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetDirPortUsesIn")
    @ResponseWrapper(localName = "setDirPortUsesInResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mBgExec.SetDirPortUsesInResponse")
    @Action(input = "http://be.montage.ufc.br/I_mBgExec/setDirPortUsesInRequest", output = "http://be.montage.ufc.br/I_mBgExec/setDirPortUsesInResponse")
    public void setDirPortUsesIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
