
package br.montage.stubs.mArchiveList;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_mArchiveListImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10015/mArchiveList?wsdl")
public class IMArchiveListImplService
    extends Service
{

    private final static URL IMARCHIVELISTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMARCHIVELISTIMPLSERVICE_EXCEPTION;
    private final static QName IMARCHIVELISTIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_mArchiveListImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10015/mArchiveList?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMARCHIVELISTIMPLSERVICE_WSDL_LOCATION = url;
        IMARCHIVELISTIMPLSERVICE_EXCEPTION = e;
    }

    public IMArchiveListImplService() {
        super(__getWsdlLocation(), IMARCHIVELISTIMPLSERVICE_QNAME);
    }

    public IMArchiveListImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMARCHIVELISTIMPLSERVICE_QNAME, features);
    }

    public IMArchiveListImplService(URL wsdlLocation) {
        super(wsdlLocation, IMARCHIVELISTIMPLSERVICE_QNAME);
    }

    public IMArchiveListImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMARCHIVELISTIMPLSERVICE_QNAME, features);
    }

    public IMArchiveListImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMArchiveListImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMArchiveList
     */
    @WebEndpoint(name = "I_mArchiveListImplPort")
    public IMArchiveList getIMArchiveListImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mArchiveListImplPort"), IMArchiveList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMArchiveList
     */
    @WebEndpoint(name = "I_mArchiveListImplPort")
    public IMArchiveList getIMArchiveListImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mArchiveListImplPort"), IMArchiveList.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMARCHIVELISTIMPLSERVICE_EXCEPTION!= null) {
            throw IMARCHIVELISTIMPLSERVICE_EXCEPTION;
        }
        return IMARCHIVELISTIMPLSERVICE_WSDL_LOCATION;
    }

}
