
package br.montage.stubs.mArchiveList;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mArchiveList", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMArchiveList {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveList.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveList.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mArchiveList/goRequest", output = "http://be.montage.ufc.br/I_mArchiveList/goResponse")
    public void go();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTblProvides", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveList.GetTblProvides")
    @ResponseWrapper(localName = "getTblProvidesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveList.GetTblProvidesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mArchiveList/getTblProvidesRequest", output = "http://be.montage.ufc.br/I_mArchiveList/getTblProvidesResponse")
    public String getTblProvides();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setRawUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveList.SetRawUses")
    @ResponseWrapper(localName = "setRawUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveList.SetRawUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mArchiveList/setRawUsesRequest", output = "http://be.montage.ufc.br/I_mArchiveList/setRawUsesResponse")
    public void setRawUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
