
package br.ufc.m101.stubs.mimgtbl.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MImgtblTskPortImplService", targetNamespace = "http://mimgtbl.component.m101.ufc.br/", wsdlLocation = "http://localhost:11411/mimgtbl-tsk?wsdl")
public class MImgtblTskPortImplService
    extends Service
{

    private final static URL MIMGTBLTSKPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MIMGTBLTSKPORTIMPLSERVICE_EXCEPTION;
    private final static QName MIMGTBLTSKPORTIMPLSERVICE_QNAME = new QName("http://mimgtbl.component.m101.ufc.br/", "MImgtblTskPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11411/mimgtbl-tsk?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MIMGTBLTSKPORTIMPLSERVICE_WSDL_LOCATION = url;
        MIMGTBLTSKPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MImgtblTskPortImplService() {
        super(__getWsdlLocation(), MIMGTBLTSKPORTIMPLSERVICE_QNAME);
    }

    public MImgtblTskPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MIMGTBLTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MImgtblTskPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MIMGTBLTSKPORTIMPLSERVICE_QNAME);
    }

    public MImgtblTskPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MIMGTBLTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MImgtblTskPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MImgtblTskPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MImgtblTskPort
     */
    @WebEndpoint(name = "MImgtblTskPortImplPort")
    public MImgtblTskPort getMImgtblTskPortImplPort() {
        return super.getPort(new QName("http://mimgtbl.component.m101.ufc.br/", "MImgtblTskPortImplPort"), MImgtblTskPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MImgtblTskPort
     */
    @WebEndpoint(name = "MImgtblTskPortImplPort")
    public MImgtblTskPort getMImgtblTskPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mimgtbl.component.m101.ufc.br/", "MImgtblTskPortImplPort"), MImgtblTskPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MIMGTBLTSKPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MIMGTBLTSKPORTIMPLSERVICE_EXCEPTION;
        }
        return MIMGTBLTSKPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
