
package br.montage.stubs.mProjExec;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_mProjExecImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10013/mProjExec?wsdl")
public class IMProjExecImplService
    extends Service
{

    private final static URL IMPROJEXECIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMPROJEXECIMPLSERVICE_EXCEPTION;
    private final static QName IMPROJEXECIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_mProjExecImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10013/mProjExec?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMPROJEXECIMPLSERVICE_WSDL_LOCATION = url;
        IMPROJEXECIMPLSERVICE_EXCEPTION = e;
    }

    public IMProjExecImplService() {
        super(__getWsdlLocation(), IMPROJEXECIMPLSERVICE_QNAME);
    }

    public IMProjExecImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMPROJEXECIMPLSERVICE_QNAME, features);
    }

    public IMProjExecImplService(URL wsdlLocation) {
        super(wsdlLocation, IMPROJEXECIMPLSERVICE_QNAME);
    }

    public IMProjExecImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMPROJEXECIMPLSERVICE_QNAME, features);
    }

    public IMProjExecImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMProjExecImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMProjExec
     */
    @WebEndpoint(name = "I_mProjExecImplPort")
    public IMProjExec getIMProjExecImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mProjExecImplPort"), IMProjExec.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMProjExec
     */
    @WebEndpoint(name = "I_mProjExecImplPort")
    public IMProjExec getIMProjExecImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mProjExecImplPort"), IMProjExec.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMPROJEXECIMPLSERVICE_EXCEPTION!= null) {
            throw IMPROJEXECIMPLSERVICE_EXCEPTION;
        }
        return IMPROJEXECIMPLSERVICE_WSDL_LOCATION;
    }

}
