
package br.montage.stubs.mProjExec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mProjExec", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMProjExec {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetTblPortUses")
    @ResponseWrapper(localName = "setTblPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetTblPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mProjExec/setTblPortUsesRequest", output = "http://be.montage.ufc.br/I_mProjExec/setTblPortUsesResponse")
    public void setTblPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setHdrPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetHdrPortUses")
    @ResponseWrapper(localName = "setHdrPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetHdrPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mProjExec/setHdrPortUsesRequest", output = "http://be.montage.ufc.br/I_mProjExec/setHdrPortUsesResponse")
    public void setHdrPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mProjExec/goRequest", output = "http://be.montage.ufc.br/I_mProjExec/goResponse")
    public void go();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUsesOut", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetDirPortUsesOut")
    @ResponseWrapper(localName = "setDirPortUsesOutResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetDirPortUsesOutResponse")
    @Action(input = "http://be.montage.ufc.br/I_mProjExec/setDirPortUsesOutRequest", output = "http://be.montage.ufc.br/I_mProjExec/setDirPortUsesOutResponse")
    public void setDirPortUsesOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUsesIn", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetDirPortUsesIn")
    @ResponseWrapper(localName = "setDirPortUsesInResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.SetDirPortUsesInResponse")
    @Action(input = "http://be.montage.ufc.br/I_mProjExec/setDirPortUsesInRequest", output = "http://be.montage.ufc.br/I_mProjExec/setDirPortUsesInResponse")
    public void setDirPortUsesIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTblPortProvides", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.GetTblPortProvides")
    @ResponseWrapper(localName = "getTblPortProvidesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mProjExec.GetTblPortProvidesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mProjExec/getTblPortProvidesRequest", output = "http://be.montage.ufc.br/I_mProjExec/getTblPortProvidesResponse")
    public String getTblPortProvides();

}
