
package br.ufc.mdcc.pargo.safe.sample.stubs.server.task;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceServerTask", targetNamespace = "http://tsk.port.server.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceServerTask {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "connect", targetNamespace = "http://tsk.port.server.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.stubs.server.task.Connect")
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://tsk.port.server.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.stubs.server.task.ConnectResponse")
    @Action(input = "http://tsk.port.server.safe.pargo.mdcc.ufc.br/IServiceServerTask/connectRequest", output = "http://tsk.port.server.safe.pargo.mdcc.ufc.br/IServiceServerTask/connectResponse")
    public void connect();

}
