
package br.ufc.safe.sample.stubs.app_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AppRequestMessageEnvPortServiceService", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/", wsdlLocation = "http://localhost:10008/app-req?wsdl")
public class AppRequestMessageEnvPortServiceService
    extends Service
{

    private final static URL APPREQUESTMESSAGEENVPORTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException APPREQUESTMESSAGEENVPORTSERVICESERVICE_EXCEPTION;
    private final static QName APPREQUESTMESSAGEENVPORTSERVICESERVICE_QNAME = new QName("http://service.prt.app.sample.safe.ufc.br/", "AppRequestMessageEnvPortServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10008/app-req?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPREQUESTMESSAGEENVPORTSERVICESERVICE_WSDL_LOCATION = url;
        APPREQUESTMESSAGEENVPORTSERVICESERVICE_EXCEPTION = e;
    }

    public AppRequestMessageEnvPortServiceService() {
        super(__getWsdlLocation(), APPREQUESTMESSAGEENVPORTSERVICESERVICE_QNAME);
    }

    public AppRequestMessageEnvPortServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPREQUESTMESSAGEENVPORTSERVICESERVICE_QNAME, features);
    }

    public AppRequestMessageEnvPortServiceService(URL wsdlLocation) {
        super(wsdlLocation, APPREQUESTMESSAGEENVPORTSERVICESERVICE_QNAME);
    }

    public AppRequestMessageEnvPortServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPREQUESTMESSAGEENVPORTSERVICESERVICE_QNAME, features);
    }

    public AppRequestMessageEnvPortServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppRequestMessageEnvPortServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAppRequestMessageEnvPortService
     */
    @WebEndpoint(name = "AppRequestMessageEnvPortServicePort")
    public IAppRequestMessageEnvPortService getAppRequestMessageEnvPortServicePort() {
        return super.getPort(new QName("http://service.prt.app.sample.safe.ufc.br/", "AppRequestMessageEnvPortServicePort"), IAppRequestMessageEnvPortService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAppRequestMessageEnvPortService
     */
    @WebEndpoint(name = "AppRequestMessageEnvPortServicePort")
    public IAppRequestMessageEnvPortService getAppRequestMessageEnvPortServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.prt.app.sample.safe.ufc.br/", "AppRequestMessageEnvPortServicePort"), IAppRequestMessageEnvPortService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPREQUESTMESSAGEENVPORTSERVICESERVICE_EXCEPTION!= null) {
            throw APPREQUESTMESSAGEENVPORTSERVICESERVICE_EXCEPTION;
        }
        return APPREQUESTMESSAGEENVPORTSERVICESERVICE_WSDL_LOCATION;
    }

}
