
package br.ufc.safe.sample.stubs.app_0;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAppRequestMessageEnvPortService", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAppRequestMessageEnvPortService {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "requestMessage", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.app_0.RequestMessage")
    @ResponseWrapper(localName = "requestMessageResponse", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.app_0.RequestMessageResponse")
    @Action(input = "http://service.prt.app.sample.safe.ufc.br/IAppRequestMessageEnvPortService/requestMessageRequest", output = "http://service.prt.app.sample.safe.ufc.br/IAppRequestMessageEnvPortService/requestMessageResponse")
    public void requestMessage();

}
