
package br.ufc.mdcc.pargo.safe.sample.stubs.server.env;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceServerEnv", targetNamespace = "http://env.port.server.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceServerEnv {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPort", targetNamespace = "http://env.port.server.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.stubs.server.env.SetPort")
    @ResponseWrapper(localName = "setPortResponse", targetNamespace = "http://env.port.server.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.stubs.server.env.SetPortResponse")
    @Action(input = "http://env.port.server.safe.pargo.mdcc.ufc.br/IServiceServerEnv/setPortRequest", output = "http://env.port.server.safe.pargo.mdcc.ufc.br/IServiceServerEnv/setPortResponse")
    public void setPort(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
