
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceClientEnvImplService", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10005/client-env?wsdl")
public class ServiceClientEnvImplService
    extends Service
{

    private final static URL SERVICECLIENTENVIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECLIENTENVIMPLSERVICE_EXCEPTION;
    private final static QName SERVICECLIENTENVIMPLSERVICE_QNAME = new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceClientEnvImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10005/client-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECLIENTENVIMPLSERVICE_WSDL_LOCATION = url;
        SERVICECLIENTENVIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceClientEnvImplService() {
        super(__getWsdlLocation(), SERVICECLIENTENVIMPLSERVICE_QNAME);
    }

    public ServiceClientEnvImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECLIENTENVIMPLSERVICE_QNAME, features);
    }

    public ServiceClientEnvImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECLIENTENVIMPLSERVICE_QNAME);
    }

    public ServiceClientEnvImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECLIENTENVIMPLSERVICE_QNAME, features);
    }

    public ServiceClientEnvImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceClientEnvImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceIClientEnv
     */
    @WebEndpoint(name = "ServiceClientEnvImplPort")
    public ServiceIClientEnv getServiceClientEnvImplPort() {
        return super.getPort(new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceClientEnvImplPort"), ServiceIClientEnv.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceIClientEnv
     */
    @WebEndpoint(name = "ServiceClientEnvImplPort")
    public ServiceIClientEnv getServiceClientEnvImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceClientEnvImplPort"), ServiceIClientEnv.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECLIENTENVIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICECLIENTENVIMPLSERVICE_EXCEPTION;
        }
        return SERVICECLIENTENVIMPLSERVICE_WSDL_LOCATION;
    }

}
