
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.env;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceIClientEnv", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceIClientEnv {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMsg", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.env.SendMsg")
    @ResponseWrapper(localName = "sendMsgResponse", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.env.SendMsgResponse")
    @Action(input = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIClientEnv/sendMsgRequest", output = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIClientEnv/sendMsgResponse")
    public void sendMsg(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
