
package br.ufc.m101.stubs.mprojexec.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MProjExecEnvPortImplService", targetNamespace = "http://mprojexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11416/mprojexec-env?wsdl")
public class MProjExecEnvPortImplService
    extends Service
{

    private final static URL MPROJEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MPROJEXECENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MPROJEXECENVPORTIMPLSERVICE_QNAME = new QName("http://mprojexec.component.m101.ufc.br/", "MProjExecEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11416/mprojexec-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MPROJEXECENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MPROJEXECENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MProjExecEnvPortImplService() {
        super(__getWsdlLocation(), MPROJEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MProjExecEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MPROJEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MProjExecEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MPROJEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MProjExecEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MPROJEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MProjExecEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MProjExecEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MProjExecEnvPort
     */
    @WebEndpoint(name = "MProjExecEnvPortImplPort")
    public MProjExecEnvPort getMProjExecEnvPortImplPort() {
        return super.getPort(new QName("http://mprojexec.component.m101.ufc.br/", "MProjExecEnvPortImplPort"), MProjExecEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MProjExecEnvPort
     */
    @WebEndpoint(name = "MProjExecEnvPortImplPort")
    public MProjExecEnvPort getMProjExecEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mprojexec.component.m101.ufc.br/", "MProjExecEnvPortImplPort"), MProjExecEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MPROJEXECENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MPROJEXECENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MPROJEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
