
package br.ufc.mdcc.pargo.safe.framework.application.biding.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HShelfApplicationBidingServerWSService", targetNamespace = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10011/app-env?wsdl")
public class HShelfApplicationBidingServerWSService
    extends Service
{

    private final static URL HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_EXCEPTION;
    private final static QName HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_QNAME = new QName("http://biding.application.framework.safe.pargo.mdcc.ufc.br/", "HShelfApplicationBidingServerWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10011/app-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_WSDL_LOCATION = url;
        HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_EXCEPTION = e;
    }

    public HShelfApplicationBidingServerWSService() {
        super(__getWsdlLocation(), HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_QNAME);
    }

    public HShelfApplicationBidingServerWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_QNAME, features);
    }

    public HShelfApplicationBidingServerWSService(URL wsdlLocation) {
        super(wsdlLocation, HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_QNAME);
    }

    public HShelfApplicationBidingServerWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_QNAME, features);
    }

    public HShelfApplicationBidingServerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HShelfApplicationBidingServerWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHShelfApplicationBidingServerWS
     */
    @WebEndpoint(name = "HShelfApplicationBidingServerWSPort")
    public IHShelfApplicationBidingServerWS getHShelfApplicationBidingServerWSPort() {
        return super.getPort(new QName("http://biding.application.framework.safe.pargo.mdcc.ufc.br/", "HShelfApplicationBidingServerWSPort"), IHShelfApplicationBidingServerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHShelfApplicationBidingServerWS
     */
    @WebEndpoint(name = "HShelfApplicationBidingServerWSPort")
    public IHShelfApplicationBidingServerWS getHShelfApplicationBidingServerWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://biding.application.framework.safe.pargo.mdcc.ufc.br/", "HShelfApplicationBidingServerWSPort"), IHShelfApplicationBidingServerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_EXCEPTION!= null) {
            throw HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_EXCEPTION;
        }
        return HSHELFAPPLICATIONBIDINGSERVERWSSERVICE_WSDL_LOCATION;
    }

}
