
package br.ufc.mdcc.pargo.safe.framework.application.biding.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHShelfApplicationBidingServerWS", targetNamespace = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHShelfApplicationBidingServerWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setApplicationFacade", targetNamespace = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.application.biding.stubs.SetApplicationFacade")
    @ResponseWrapper(localName = "setApplicationFacadeResponse", targetNamespace = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.application.biding.stubs.SetApplicationFacadeResponse")
    @Action(input = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/IHShelfApplicationBidingServerWS/setApplicationFacadeRequest", output = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/IHShelfApplicationBidingServerWS/setApplicationFacadeResponse")
    public void setApplicationFacade(
        @WebParam(name = "arg0", targetNamespace = "")
        HShelfApplicationBidingServerFacade arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "service", targetNamespace = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.application.biding.stubs.Service")
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.application.biding.stubs.ServiceResponse")
    @Action(input = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/IHShelfApplicationBidingServerWS/serviceRequest", output = "http://biding.application.framework.safe.pargo.mdcc.ufc.br/IHShelfApplicationBidingServerWS/serviceResponse")
    public void service(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
