
package br.ufc.m101.stubs.mbgmodel.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MBgModelEnvPortImplService", targetNamespace = "http://mbgmodel.component.m101.ufc.br/", wsdlLocation = "http://localhost:11404/mbgmodel-env?wsdl")
public class MBgModelEnvPortImplService
    extends Service
{

    private final static URL MBGMODELENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MBGMODELENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MBGMODELENVPORTIMPLSERVICE_QNAME = new QName("http://mbgmodel.component.m101.ufc.br/", "MBgModelEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11404/mbgmodel-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MBGMODELENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MBGMODELENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MBgModelEnvPortImplService() {
        super(__getWsdlLocation(), MBGMODELENVPORTIMPLSERVICE_QNAME);
    }

    public MBgModelEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MBGMODELENVPORTIMPLSERVICE_QNAME, features);
    }

    public MBgModelEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MBGMODELENVPORTIMPLSERVICE_QNAME);
    }

    public MBgModelEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MBGMODELENVPORTIMPLSERVICE_QNAME, features);
    }

    public MBgModelEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MBgModelEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MBgModelEnvPort
     */
    @WebEndpoint(name = "MBgModelEnvPortImplPort")
    public MBgModelEnvPort getMBgModelEnvPortImplPort() {
        return super.getPort(new QName("http://mbgmodel.component.m101.ufc.br/", "MBgModelEnvPortImplPort"), MBgModelEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MBgModelEnvPort
     */
    @WebEndpoint(name = "MBgModelEnvPortImplPort")
    public MBgModelEnvPort getMBgModelEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mbgmodel.component.m101.ufc.br/", "MBgModelEnvPortImplPort"), MBgModelEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MBGMODELENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MBGMODELENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MBGMODELENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
