
package br.ufc.safe.sample.stubs.app_1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AppReturnMessageEnvPortServiceService", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/", wsdlLocation = "http://localhost:10009/app-ret?wsdl")
public class AppReturnMessageEnvPortServiceService
    extends Service
{

    private final static URL APPRETURNMESSAGEENVPORTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException APPRETURNMESSAGEENVPORTSERVICESERVICE_EXCEPTION;
    private final static QName APPRETURNMESSAGEENVPORTSERVICESERVICE_QNAME = new QName("http://service.prt.app.sample.safe.ufc.br/", "AppReturnMessageEnvPortServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10009/app-ret?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPRETURNMESSAGEENVPORTSERVICESERVICE_WSDL_LOCATION = url;
        APPRETURNMESSAGEENVPORTSERVICESERVICE_EXCEPTION = e;
    }

    public AppReturnMessageEnvPortServiceService() {
        super(__getWsdlLocation(), APPRETURNMESSAGEENVPORTSERVICESERVICE_QNAME);
    }

    public AppReturnMessageEnvPortServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPRETURNMESSAGEENVPORTSERVICESERVICE_QNAME, features);
    }

    public AppReturnMessageEnvPortServiceService(URL wsdlLocation) {
        super(wsdlLocation, APPRETURNMESSAGEENVPORTSERVICESERVICE_QNAME);
    }

    public AppReturnMessageEnvPortServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPRETURNMESSAGEENVPORTSERVICESERVICE_QNAME, features);
    }

    public AppReturnMessageEnvPortServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppReturnMessageEnvPortServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAppReturnMessageEnvPortService
     */
    @WebEndpoint(name = "AppReturnMessageEnvPortServicePort")
    public IAppReturnMessageEnvPortService getAppReturnMessageEnvPortServicePort() {
        return super.getPort(new QName("http://service.prt.app.sample.safe.ufc.br/", "AppReturnMessageEnvPortServicePort"), IAppReturnMessageEnvPortService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAppReturnMessageEnvPortService
     */
    @WebEndpoint(name = "AppReturnMessageEnvPortServicePort")
    public IAppReturnMessageEnvPortService getAppReturnMessageEnvPortServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.prt.app.sample.safe.ufc.br/", "AppReturnMessageEnvPortServicePort"), IAppReturnMessageEnvPortService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPRETURNMESSAGEENVPORTSERVICESERVICE_EXCEPTION!= null) {
            throw APPRETURNMESSAGEENVPORTSERVICESERVICE_EXCEPTION;
        }
        return APPRETURNMESSAGEENVPORTSERVICESERVICE_WSDL_LOCATION;
    }

}
