
package br.ufc.safe.sample.stubs.app_1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAppReturnMessageEnvPortService", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAppReturnMessageEnvPortService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "returnMessage", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.app_1.ReturnMessage")
    @ResponseWrapper(localName = "returnMessageResponse", targetNamespace = "http://service.prt.app.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.app_1.ReturnMessageResponse")
    @Action(input = "http://service.prt.app.sample.safe.ufc.br/IAppReturnMessageEnvPortService/returnMessageRequest", output = "http://service.prt.app.sample.safe.ufc.br/IAppReturnMessageEnvPortService/returnMessageResponse")
    public void returnMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
