
package br.montage.stubs.mFitExec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mFitExec", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMFitExec {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.SetTblPortUses")
    @ResponseWrapper(localName = "setTblPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.SetTblPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mFitExec/setTblPortUsesRequest", output = "http://be.montage.ufc.br/I_mFitExec/setTblPortUsesResponse")
    public void setTblPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.SetDirPortUses")
    @ResponseWrapper(localName = "setDirPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.SetDirPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mFitExec/setDirPortUsesRequest", output = "http://be.montage.ufc.br/I_mFitExec/setDirPortUsesResponse")
    public void setDirPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mFitExec/goRequest", output = "http://be.montage.ufc.br/I_mFitExec/goResponse")
    public void go();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTblPortProvides", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.GetTblPortProvides")
    @ResponseWrapper(localName = "getTblPortProvidesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mFitExec.GetTblPortProvidesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mFitExec/getTblPortProvidesRequest", output = "http://be.montage.ufc.br/I_mFitExec/getTblPortProvidesResponse")
    public String getTblPortProvides();

}
