
package br.ufc.m101.stubs.mprojexec.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MProjExecPortImplService", targetNamespace = "http://mprojexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11417/mprojexec-tsk?wsdl")
public class MProjExecPortImplService
    extends Service
{

    private final static URL MPROJEXECPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MPROJEXECPORTIMPLSERVICE_EXCEPTION;
    private final static QName MPROJEXECPORTIMPLSERVICE_QNAME = new QName("http://mprojexec.component.m101.ufc.br/", "MProjExecPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11417/mprojexec-tsk?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MPROJEXECPORTIMPLSERVICE_WSDL_LOCATION = url;
        MPROJEXECPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MProjExecPortImplService() {
        super(__getWsdlLocation(), MPROJEXECPORTIMPLSERVICE_QNAME);
    }

    public MProjExecPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MPROJEXECPORTIMPLSERVICE_QNAME, features);
    }

    public MProjExecPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MPROJEXECPORTIMPLSERVICE_QNAME);
    }

    public MProjExecPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MPROJEXECPORTIMPLSERVICE_QNAME, features);
    }

    public MProjExecPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MProjExecPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MProjExecTskPort
     */
    @WebEndpoint(name = "MProjExecPortImplPort")
    public MProjExecTskPort getMProjExecPortImplPort() {
        return super.getPort(new QName("http://mprojexec.component.m101.ufc.br/", "MProjExecPortImplPort"), MProjExecTskPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MProjExecTskPort
     */
    @WebEndpoint(name = "MProjExecPortImplPort")
    public MProjExecTskPort getMProjExecPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mprojexec.component.m101.ufc.br/", "MProjExecPortImplPort"), MProjExecTskPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MPROJEXECPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MPROJEXECPORTIMPLSERVICE_EXCEPTION;
        }
        return MPROJEXECPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
