
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.server.go;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSIServerConsumerGoPortImplService", targetNamespace = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10002/server-go?wsdl")
public class WSIServerConsumerGoPortImplService
    extends Service
{

    private final static URL WSISERVERCONSUMERGOPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSISERVERCONSUMERGOPORTIMPLSERVICE_EXCEPTION;
    private final static QName WSISERVERCONSUMERGOPORTIMPLSERVICE_QNAME = new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIServerConsumerGoPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10002/server-go?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSISERVERCONSUMERGOPORTIMPLSERVICE_WSDL_LOCATION = url;
        WSISERVERCONSUMERGOPORTIMPLSERVICE_EXCEPTION = e;
    }

    public WSIServerConsumerGoPortImplService() {
        super(__getWsdlLocation(), WSISERVERCONSUMERGOPORTIMPLSERVICE_QNAME);
    }

    public WSIServerConsumerGoPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSISERVERCONSUMERGOPORTIMPLSERVICE_QNAME, features);
    }

    public WSIServerConsumerGoPortImplService(URL wsdlLocation) {
        super(wsdlLocation, WSISERVERCONSUMERGOPORTIMPLSERVICE_QNAME);
    }

    public WSIServerConsumerGoPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSISERVERCONSUMERGOPORTIMPLSERVICE_QNAME, features);
    }

    public WSIServerConsumerGoPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSIServerConsumerGoPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSIServerConsumerGoPort
     */
    @WebEndpoint(name = "WSIServerConsumerGoPortImplPort")
    public WSIServerConsumerGoPort getWSIServerConsumerGoPortImplPort() {
        return super.getPort(new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIServerConsumerGoPortImplPort"), WSIServerConsumerGoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSIServerConsumerGoPort
     */
    @WebEndpoint(name = "WSIServerConsumerGoPortImplPort")
    public WSIServerConsumerGoPort getWSIServerConsumerGoPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIServerConsumerGoPortImplPort"), WSIServerConsumerGoPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSISERVERCONSUMERGOPORTIMPLSERVICE_EXCEPTION!= null) {
            throw WSISERVERCONSUMERGOPORTIMPLSERVICE_EXCEPTION;
        }
        return WSISERVERCONSUMERGOPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
