
package br.ufc.m101.stubs.mbgexec.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MBgExecTskPortImplService", targetNamespace = "http://mbgexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11403/mbgexec-tsk?wsdl")
public class MBgExecTskPortImplService
    extends Service
{

    private final static URL MBGEXECTSKPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MBGEXECTSKPORTIMPLSERVICE_EXCEPTION;
    private final static QName MBGEXECTSKPORTIMPLSERVICE_QNAME = new QName("http://mbgexec.component.m101.ufc.br/", "MBgExecTskPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11403/mbgexec-tsk?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MBGEXECTSKPORTIMPLSERVICE_WSDL_LOCATION = url;
        MBGEXECTSKPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MBgExecTskPortImplService() {
        super(__getWsdlLocation(), MBGEXECTSKPORTIMPLSERVICE_QNAME);
    }

    public MBgExecTskPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MBGEXECTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MBgExecTskPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MBGEXECTSKPORTIMPLSERVICE_QNAME);
    }

    public MBgExecTskPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MBGEXECTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MBgExecTskPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MBgExecTskPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MBgExecTskPortImpl
     */
    @WebEndpoint(name = "MBgExecTskPortImplPort")
    public MBgExecTskPortImpl getMBgExecTskPortImplPort() {
        return super.getPort(new QName("http://mbgexec.component.m101.ufc.br/", "MBgExecTskPortImplPort"), MBgExecTskPortImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MBgExecTskPortImpl
     */
    @WebEndpoint(name = "MBgExecTskPortImplPort")
    public MBgExecTskPortImpl getMBgExecTskPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mbgexec.component.m101.ufc.br/", "MBgExecTskPortImplPort"), MBgExecTskPortImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MBGEXECTSKPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MBGEXECTSKPORTIMPLSERVICE_EXCEPTION;
        }
        return MBGEXECTSKPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
