
package br.ufc.m101.stubs.mjpeg.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MJpegEnvPortImplService", targetNamespace = "http://mjpeg.component.m101.ufc.br/", wsdlLocation = "http://localhost:11412/mjpeg-env?wsdl")
public class MJpegEnvPortImplService
    extends Service
{

    private final static URL MJPEGENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MJPEGENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MJPEGENVPORTIMPLSERVICE_QNAME = new QName("http://mjpeg.component.m101.ufc.br/", "MJpegEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11412/mjpeg-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MJPEGENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MJPEGENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MJpegEnvPortImplService() {
        super(__getWsdlLocation(), MJPEGENVPORTIMPLSERVICE_QNAME);
    }

    public MJpegEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MJPEGENVPORTIMPLSERVICE_QNAME, features);
    }

    public MJpegEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MJPEGENVPORTIMPLSERVICE_QNAME);
    }

    public MJpegEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MJPEGENVPORTIMPLSERVICE_QNAME, features);
    }

    public MJpegEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MJpegEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MJpegEnvPort
     */
    @WebEndpoint(name = "MJpegEnvPortImplPort")
    public MJpegEnvPort getMJpegEnvPortImplPort() {
        return super.getPort(new QName("http://mjpeg.component.m101.ufc.br/", "MJpegEnvPortImplPort"), MJpegEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MJpegEnvPort
     */
    @WebEndpoint(name = "MJpegEnvPortImplPort")
    public MJpegEnvPort getMJpegEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mjpeg.component.m101.ufc.br/", "MJpegEnvPortImplPort"), MJpegEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MJPEGENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MJPEGENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MJPEGENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
