
package br.montage.stubs.mMontageDir;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_MontageDirImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10011/mMontageDir?wsdl")
public class IMontageDirImplService
    extends Service
{

    private final static URL IMONTAGEDIRIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMONTAGEDIRIMPLSERVICE_EXCEPTION;
    private final static QName IMONTAGEDIRIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_MontageDirImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10011/mMontageDir?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMONTAGEDIRIMPLSERVICE_WSDL_LOCATION = url;
        IMONTAGEDIRIMPLSERVICE_EXCEPTION = e;
    }

    public IMontageDirImplService() {
        super(__getWsdlLocation(), IMONTAGEDIRIMPLSERVICE_QNAME);
    }

    public IMontageDirImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMONTAGEDIRIMPLSERVICE_QNAME, features);
    }

    public IMontageDirImplService(URL wsdlLocation) {
        super(wsdlLocation, IMONTAGEDIRIMPLSERVICE_QNAME);
    }

    public IMontageDirImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMONTAGEDIRIMPLSERVICE_QNAME, features);
    }

    public IMontageDirImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMontageDirImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMontageDir
     */
    @WebEndpoint(name = "I_MontageDirImplPort")
    public IMontageDir getIMontageDirImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_MontageDirImplPort"), IMontageDir.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMontageDir
     */
    @WebEndpoint(name = "I_MontageDirImplPort")
    public IMontageDir getIMontageDirImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_MontageDirImplPort"), IMontageDir.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMONTAGEDIRIMPLSERVICE_EXCEPTION!= null) {
            throw IMONTAGEDIRIMPLSERVICE_EXCEPTION;
        }
        return IMONTAGEDIRIMPLSERVICE_WSDL_LOCATION;
    }

}
