
package br.ufc.mdcc.pargo.backend.safeport.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientServerApplicationServiceImplService", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10020/app-port?wsdl")
public class ClientServerApplicationServiceImplService
    extends Service
{

    private final static URL CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_QNAME = new QName("http://service.sample.safe.pargo.mdcc.ufc.br/", "ClientServerApplicationServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10020/app-port?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ClientServerApplicationServiceImplService() {
        super(__getWsdlLocation(), CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_QNAME);
    }

    public ClientServerApplicationServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public ClientServerApplicationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_QNAME);
    }

    public ClientServerApplicationServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_QNAME, features);
    }

    public ClientServerApplicationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientServerApplicationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IClientServerApplicationService
     */
    @WebEndpoint(name = "ClientServerApplicationServiceImplPort")
    public IClientServerApplicationService getClientServerApplicationServiceImplPort() {
        return super.getPort(new QName("http://service.sample.safe.pargo.mdcc.ufc.br/", "ClientServerApplicationServiceImplPort"), IClientServerApplicationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IClientServerApplicationService
     */
    @WebEndpoint(name = "ClientServerApplicationServiceImplPort")
    public IClientServerApplicationService getClientServerApplicationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sample.safe.pargo.mdcc.ufc.br/", "ClientServerApplicationServiceImplPort"), IClientServerApplicationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CLIENTSERVERAPPLICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
