
package br.ufc.mdcc.pargo.backend.safeport.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IClientServerApplicationService", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IClientServerApplicationService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setApplicationPort", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.safeport.stubs.SetApplicationPort")
    @ResponseWrapper(localName = "setApplicationPortResponse", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.safeport.stubs.SetApplicationPortResponse")
    @Action(input = "http://service.sample.safe.pargo.mdcc.ufc.br/IClientServerApplicationService/setApplicationPortRequest", output = "http://service.sample.safe.pargo.mdcc.ufc.br/IClientServerApplicationService/setApplicationPortResponse")
    public void setApplicationPort(
        @WebParam(name = "arg0", targetNamespace = "")
        ClientServerApplicationPort arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "requestMessage", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.safeport.stubs.RequestMessage")
    @ResponseWrapper(localName = "requestMessageResponse", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.safeport.stubs.RequestMessageResponse")
    @Action(input = "http://service.sample.safe.pargo.mdcc.ufc.br/IClientServerApplicationService/requestMessageRequest", output = "http://service.sample.safe.pargo.mdcc.ufc.br/IClientServerApplicationService/requestMessageResponse")
    public void requestMessage();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.safeport.stubs.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://service.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.safeport.stubs.SendMessageResponse")
    @Action(input = "http://service.sample.safe.pargo.mdcc.ufc.br/IClientServerApplicationService/sendMessageRequest", output = "http://service.sample.safe.pargo.mdcc.ufc.br/IClientServerApplicationService/sendMessageResponse")
    public void sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
