
package br.ufc.m101.stubs.mjpeg.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MJpegTskPortImplService", targetNamespace = "http://mjpeg.component.m101.ufc.br/", wsdlLocation = "http://localhost:11413/mjpeg-tsk?wsdl")
public class MJpegTskPortImplService
    extends Service
{

    private final static URL MJPEGTSKPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MJPEGTSKPORTIMPLSERVICE_EXCEPTION;
    private final static QName MJPEGTSKPORTIMPLSERVICE_QNAME = new QName("http://mjpeg.component.m101.ufc.br/", "MJpegTskPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11413/mjpeg-tsk?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MJPEGTSKPORTIMPLSERVICE_WSDL_LOCATION = url;
        MJPEGTSKPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MJpegTskPortImplService() {
        super(__getWsdlLocation(), MJPEGTSKPORTIMPLSERVICE_QNAME);
    }

    public MJpegTskPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MJPEGTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MJpegTskPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MJPEGTSKPORTIMPLSERVICE_QNAME);
    }

    public MJpegTskPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MJPEGTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MJpegTskPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MJpegTskPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MJpegTskPort
     */
    @WebEndpoint(name = "MJpegTskPortImplPort")
    public MJpegTskPort getMJpegTskPortImplPort() {
        return super.getPort(new QName("http://mjpeg.component.m101.ufc.br/", "MJpegTskPortImplPort"), MJpegTskPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MJpegTskPort
     */
    @WebEndpoint(name = "MJpegTskPortImplPort")
    public MJpegTskPort getMJpegTskPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mjpeg.component.m101.ufc.br/", "MJpegTskPortImplPort"), MJpegTskPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MJPEGTSKPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MJPEGTSKPORTIMPLSERVICE_EXCEPTION;
        }
        return MJPEGTSKPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
