
package br.ufc.m101.stubs.mimgtbl.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MImgtblEnvPortImplService", targetNamespace = "http://mimgtbl.component.m101.ufc.br/", wsdlLocation = "http://localhost:11410/mimgtbl-env?wsdl")
public class MImgtblEnvPortImplService
    extends Service
{

    private final static URL MIMGTBLENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MIMGTBLENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MIMGTBLENVPORTIMPLSERVICE_QNAME = new QName("http://mimgtbl.component.m101.ufc.br/", "MImgtblEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11410/mimgtbl-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MIMGTBLENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MIMGTBLENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MImgtblEnvPortImplService() {
        super(__getWsdlLocation(), MIMGTBLENVPORTIMPLSERVICE_QNAME);
    }

    public MImgtblEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MIMGTBLENVPORTIMPLSERVICE_QNAME, features);
    }

    public MImgtblEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MIMGTBLENVPORTIMPLSERVICE_QNAME);
    }

    public MImgtblEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MIMGTBLENVPORTIMPLSERVICE_QNAME, features);
    }

    public MImgtblEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MImgtblEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MImgtblEnvPort
     */
    @WebEndpoint(name = "MImgtblEnvPortImplPort")
    public MImgtblEnvPort getMImgtblEnvPortImplPort() {
        return super.getPort(new QName("http://mimgtbl.component.m101.ufc.br/", "MImgtblEnvPortImplPort"), MImgtblEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MImgtblEnvPort
     */
    @WebEndpoint(name = "MImgtblEnvPortImplPort")
    public MImgtblEnvPort getMImgtblEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mimgtbl.component.m101.ufc.br/", "MImgtblEnvPortImplPort"), MImgtblEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MIMGTBLENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MIMGTBLENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MIMGTBLENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
