
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.server.oper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSIServerConsumerOperationPortImplService", targetNamespace = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10003/server-operation?wsdl")
public class WSIServerConsumerOperationPortImplService
    extends Service
{

    private final static URL WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_EXCEPTION;
    private final static QName WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_QNAME = new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIServerConsumerOperationPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10003/server-operation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_WSDL_LOCATION = url;
        WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_EXCEPTION = e;
    }

    public WSIServerConsumerOperationPortImplService() {
        super(__getWsdlLocation(), WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_QNAME);
    }

    public WSIServerConsumerOperationPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_QNAME, features);
    }

    public WSIServerConsumerOperationPortImplService(URL wsdlLocation) {
        super(wsdlLocation, WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_QNAME);
    }

    public WSIServerConsumerOperationPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_QNAME, features);
    }

    public WSIServerConsumerOperationPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSIServerConsumerOperationPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSIServerConsumerOperationPort
     */
    @WebEndpoint(name = "WSIServerConsumerOperationPortImplPort")
    public WSIServerConsumerOperationPort getWSIServerConsumerOperationPortImplPort() {
        return super.getPort(new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIServerConsumerOperationPortImplPort"), WSIServerConsumerOperationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSIServerConsumerOperationPort
     */
    @WebEndpoint(name = "WSIServerConsumerOperationPortImplPort")
    public WSIServerConsumerOperationPort getWSIServerConsumerOperationPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIServerConsumerOperationPortImplPort"), WSIServerConsumerOperationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_EXCEPTION!= null) {
            throw WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_EXCEPTION;
        }
        return WSISERVERCONSUMEROPERATIONPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
