
package br.ufc.safe.sample.stubs.client.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientServiceTskService", targetNamespace = "http://client.service.sample.safe.ufc.br/", wsdlLocation = "http://localhost:10005/client-task?wsdl")
public class ClientServiceTskService
    extends Service
{

    private final static URL CLIENTSERVICETSKSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSERVICETSKSERVICE_EXCEPTION;
    private final static QName CLIENTSERVICETSKSERVICE_QNAME = new QName("http://client.service.sample.safe.ufc.br/", "ClientServiceTskService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10005/client-task?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSERVICETSKSERVICE_WSDL_LOCATION = url;
        CLIENTSERVICETSKSERVICE_EXCEPTION = e;
    }

    public ClientServiceTskService() {
        super(__getWsdlLocation(), CLIENTSERVICETSKSERVICE_QNAME);
    }

    public ClientServiceTskService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSERVICETSKSERVICE_QNAME, features);
    }

    public ClientServiceTskService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSERVICETSKSERVICE_QNAME);
    }

    public ClientServiceTskService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSERVICETSKSERVICE_QNAME, features);
    }

    public ClientServiceTskService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientServiceTskService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IClientServiceTsk
     */
    @WebEndpoint(name = "ClientServiceTskPort")
    public IClientServiceTsk getClientServiceTskPort() {
        return super.getPort(new QName("http://client.service.sample.safe.ufc.br/", "ClientServiceTskPort"), IClientServiceTsk.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IClientServiceTsk
     */
    @WebEndpoint(name = "ClientServiceTskPort")
    public IClientServiceTsk getClientServiceTskPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.service.sample.safe.ufc.br/", "ClientServiceTskPort"), IClientServiceTsk.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSERVICETSKSERVICE_EXCEPTION!= null) {
            throw CLIENTSERVICETSKSERVICE_EXCEPTION;
        }
        return CLIENTSERVICETSKSERVICE_WSDL_LOCATION;
    }

}
