
package br.ufc.safe.sample.stubs.client.tsk;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IClientServiceTsk", targetNamespace = "http://client.service.sample.safe.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IClientServiceTsk {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "post", targetNamespace = "http://client.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.client.tsk.Post")
    @ResponseWrapper(localName = "postResponse", targetNamespace = "http://client.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.client.tsk.PostResponse")
    @Action(input = "http://client.service.sample.safe.ufc.br/IClientServiceTsk/postRequest", output = "http://client.service.sample.safe.ufc.br/IClientServiceTsk/postResponse")
    public void post();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "send", targetNamespace = "http://client.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.client.tsk.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://client.service.sample.safe.ufc.br/", className = "br.ufc.safe.sample.stubs.client.tsk.SendResponse")
    @Action(input = "http://client.service.sample.safe.ufc.br/IClientServiceTsk/sendRequest", output = "http://client.service.sample.safe.ufc.br/IClientServiceTsk/sendResponse")
    public void send();

}
