
package br.ufc.m101.stubs.mbgexec.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MBgExecEnvPortImplService", targetNamespace = "http://mbgexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11402/mbgexec-env?wsdl")
public class MBgExecEnvPortImplService
    extends Service
{

    private final static URL MBGEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MBGEXECENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MBGEXECENVPORTIMPLSERVICE_QNAME = new QName("http://mbgexec.component.m101.ufc.br/", "MBgExecEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11402/mbgexec-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MBGEXECENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MBGEXECENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MBgExecEnvPortImplService() {
        super(__getWsdlLocation(), MBGEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MBgExecEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MBGEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MBgExecEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MBGEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MBgExecEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MBGEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MBgExecEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MBgExecEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MBgExecEnvPort
     */
    @WebEndpoint(name = "MBgExecEnvPortImplPort")
    public MBgExecEnvPort getMBgExecEnvPortImplPort() {
        return super.getPort(new QName("http://mbgexec.component.m101.ufc.br/", "MBgExecEnvPortImplPort"), MBgExecEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MBgExecEnvPort
     */
    @WebEndpoint(name = "MBgExecEnvPortImplPort")
    public MBgExecEnvPort getMBgExecEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mbgexec.component.m101.ufc.br/", "MBgExecEnvPortImplPort"), MBgExecEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MBGEXECENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MBGEXECENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MBGEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
