
package br.ufc.m101.stubs.mbgmodel.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MBgModelTskPortImplService", targetNamespace = "http://mbgmodel.component.m101.ufc.br/", wsdlLocation = "http://localhost:11405/mbgmodel-tsk?wsdl")
public class MBgModelTskPortImplService
    extends Service
{

    private final static URL MBGMODELTSKPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MBGMODELTSKPORTIMPLSERVICE_EXCEPTION;
    private final static QName MBGMODELTSKPORTIMPLSERVICE_QNAME = new QName("http://mbgmodel.component.m101.ufc.br/", "MBgModelTskPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11405/mbgmodel-tsk?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MBGMODELTSKPORTIMPLSERVICE_WSDL_LOCATION = url;
        MBGMODELTSKPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MBgModelTskPortImplService() {
        super(__getWsdlLocation(), MBGMODELTSKPORTIMPLSERVICE_QNAME);
    }

    public MBgModelTskPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MBGMODELTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MBgModelTskPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MBGMODELTSKPORTIMPLSERVICE_QNAME);
    }

    public MBgModelTskPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MBGMODELTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MBgModelTskPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MBgModelTskPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MBgModelTskPort
     */
    @WebEndpoint(name = "MBgModelTskPortImplPort")
    public MBgModelTskPort getMBgModelTskPortImplPort() {
        return super.getPort(new QName("http://mbgmodel.component.m101.ufc.br/", "MBgModelTskPortImplPort"), MBgModelTskPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MBgModelTskPort
     */
    @WebEndpoint(name = "MBgModelTskPortImplPort")
    public MBgModelTskPort getMBgModelTskPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mbgmodel.component.m101.ufc.br/", "MBgModelTskPortImplPort"), MBgModelTskPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MBGMODELTSKPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MBGMODELTSKPORTIMPLSERVICE_EXCEPTION;
        }
        return MBGMODELTSKPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
