
package br.ufc.mdcc.pargo.safe.framework.fcore.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IShelfCore", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IShelfCore {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "release", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.Release")
    @ResponseWrapper(localName = "releaseResponse", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.ReleaseResponse")
    @Action(input = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/releaseRequest", output = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/releaseResponse")
    public void release(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deploy", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.Deploy")
    @ResponseWrapper(localName = "deployResponse", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.DeployResponse")
    @Action(input = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/deployRequest", output = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/deployResponse")
    public String deploy(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "instantiate", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.Instantiate")
    @ResponseWrapper(localName = "instantiateResponse", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.InstantiateResponse")
    @Action(input = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/instantiateRequest", output = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/instantiateResponse")
    public String instantiate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listParameter", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.ListParameter")
    @ResponseWrapper(localName = "listParameterResponse", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.ListParameterResponse")
    @Action(input = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/listParameterRequest", output = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/listParameterResponse")
    public String listParameter(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setComponentList", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.SetComponentList")
    @ResponseWrapper(localName = "setComponentListResponse", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.SetComponentListResponse")
    @Action(input = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/setComponentListRequest", output = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/setComponentListResponse")
    public void setComponentList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resolve", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.Resolve")
    @ResponseWrapper(localName = "resolveResponse", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.framework.fcore.stub.ResolveResponse")
    @Action(input = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/resolveRequest", output = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/IShelfCore/resolveResponse")
    public String resolve(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
