
package br.ufc.mdcc.pargo.safe.framework.fcore.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShelfCoreImplService", targetNamespace = "http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:8888/core?wsdl")
public class ShelfCoreImplService
    extends Service
{

    private final static URL SHELFCOREIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SHELFCOREIMPLSERVICE_EXCEPTION;
    private final static QName SHELFCOREIMPLSERVICE_QNAME = new QName("http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", "ShelfCoreImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/core?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHELFCOREIMPLSERVICE_WSDL_LOCATION = url;
        SHELFCOREIMPLSERVICE_EXCEPTION = e;
    }

    public ShelfCoreImplService() {
        super(__getWsdlLocation(), SHELFCOREIMPLSERVICE_QNAME);
    }

    public ShelfCoreImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHELFCOREIMPLSERVICE_QNAME, features);
    }

    public ShelfCoreImplService(URL wsdlLocation) {
        super(wsdlLocation, SHELFCOREIMPLSERVICE_QNAME);
    }

    public ShelfCoreImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHELFCOREIMPLSERVICE_QNAME, features);
    }

    public ShelfCoreImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShelfCoreImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IShelfCore
     */
    @WebEndpoint(name = "ShelfCoreImplPort")
    public IShelfCore getShelfCoreImplPort() {
        return super.getPort(new QName("http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", "ShelfCoreImplPort"), IShelfCore.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IShelfCore
     */
    @WebEndpoint(name = "ShelfCoreImplPort")
    public IShelfCore getShelfCoreImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.fcore.framework.safe.pargo.mdcc.ufc.br/", "ShelfCoreImplPort"), IShelfCore.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHELFCOREIMPLSERVICE_EXCEPTION!= null) {
            throw SHELFCOREIMPLSERVICE_EXCEPTION;
        }
        return SHELFCOREIMPLSERVICE_WSDL_LOCATION;
    }

}
