
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.task;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceClientTaskImplService", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10004/client-task?wsdl")
public class ServiceClientTaskImplService
    extends Service
{

    private final static URL SERVICECLIENTTASKIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECLIENTTASKIMPLSERVICE_EXCEPTION;
    private final static QName SERVICECLIENTTASKIMPLSERVICE_QNAME = new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceClientTaskImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10004/client-task?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECLIENTTASKIMPLSERVICE_WSDL_LOCATION = url;
        SERVICECLIENTTASKIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceClientTaskImplService() {
        super(__getWsdlLocation(), SERVICECLIENTTASKIMPLSERVICE_QNAME);
    }

    public ServiceClientTaskImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECLIENTTASKIMPLSERVICE_QNAME, features);
    }

    public ServiceClientTaskImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECLIENTTASKIMPLSERVICE_QNAME);
    }

    public ServiceClientTaskImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECLIENTTASKIMPLSERVICE_QNAME, features);
    }

    public ServiceClientTaskImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceClientTaskImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceIClientTask
     */
    @WebEndpoint(name = "ServiceClientTaskImplPort")
    public ServiceIClientTask getServiceClientTaskImplPort() {
        return super.getPort(new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceClientTaskImplPort"), ServiceIClientTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceIClientTask
     */
    @WebEndpoint(name = "ServiceClientTaskImplPort")
    public ServiceIClientTask getServiceClientTaskImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceClientTaskImplPort"), ServiceIClientTask.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECLIENTTASKIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICECLIENTTASKIMPLSERVICE_EXCEPTION;
        }
        return SERVICECLIENTTASKIMPLSERVICE_WSDL_LOCATION;
    }

}
