
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.task;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceIClientTask", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceIClientTask {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setServerPort", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.task.SetServerPort")
    @ResponseWrapper(localName = "setServerPortResponse", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.task.SetServerPortResponse")
    @Action(input = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIClientTask/setServerPortRequest", output = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIClientTask/setServerPortResponse")
    public void setServerPort(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "initialize", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.task.Initialize")
    @ResponseWrapper(localName = "initializeResponse", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.task.InitializeResponse")
    @Action(input = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIClientTask/initializeRequest", output = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIClientTask/initializeResponse")
    public void initialize();

}
