
package br.ufc.mdcc.pargo.backend.server.proxy.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerProxieWSService", targetNamespace = "http://service.server.sample.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10040/server-service-port?wsdl")
public class ServerProxieWSService
    extends Service
{

    private final static URL SERVERPROXIEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERPROXIEWSSERVICE_EXCEPTION;
    private final static QName SERVERPROXIEWSSERVICE_QNAME = new QName("http://service.server.sample.safe.pargo.mdcc.ufc.br/", "ServerProxieWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10040/server-service-port?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERPROXIEWSSERVICE_WSDL_LOCATION = url;
        SERVERPROXIEWSSERVICE_EXCEPTION = e;
    }

    public ServerProxieWSService() {
        super(__getWsdlLocation(), SERVERPROXIEWSSERVICE_QNAME);
    }

    public ServerProxieWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERPROXIEWSSERVICE_QNAME, features);
    }

    public ServerProxieWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVERPROXIEWSSERVICE_QNAME);
    }

    public ServerProxieWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERPROXIEWSSERVICE_QNAME, features);
    }

    public ServerProxieWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerProxieWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServerProxieWS
     */
    @WebEndpoint(name = "ServerProxieWSPort")
    public IServerProxieWS getServerProxieWSPort() {
        return super.getPort(new QName("http://service.server.sample.safe.pargo.mdcc.ufc.br/", "ServerProxieWSPort"), IServerProxieWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServerProxieWS
     */
    @WebEndpoint(name = "ServerProxieWSPort")
    public IServerProxieWS getServerProxieWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server.sample.safe.pargo.mdcc.ufc.br/", "ServerProxieWSPort"), IServerProxieWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERPROXIEWSSERVICE_EXCEPTION!= null) {
            throw SERVERPROXIEWSSERVICE_EXCEPTION;
        }
        return SERVERPROXIEWSSERVICE_WSDL_LOCATION;
    }

}
