
package br.montage.stubs.mOverlaps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_mOverlapsImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10012/mOverlaps?wsdl")
public class IMOverlapsImplService
    extends Service
{

    private final static URL IMOVERLAPSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMOVERLAPSIMPLSERVICE_EXCEPTION;
    private final static QName IMOVERLAPSIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_mOverlapsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10012/mOverlaps?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMOVERLAPSIMPLSERVICE_WSDL_LOCATION = url;
        IMOVERLAPSIMPLSERVICE_EXCEPTION = e;
    }

    public IMOverlapsImplService() {
        super(__getWsdlLocation(), IMOVERLAPSIMPLSERVICE_QNAME);
    }

    public IMOverlapsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMOVERLAPSIMPLSERVICE_QNAME, features);
    }

    public IMOverlapsImplService(URL wsdlLocation) {
        super(wsdlLocation, IMOVERLAPSIMPLSERVICE_QNAME);
    }

    public IMOverlapsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMOVERLAPSIMPLSERVICE_QNAME, features);
    }

    public IMOverlapsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMOverlapsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMOverlaps
     */
    @WebEndpoint(name = "I_mOverlapsImplPort")
    public IMOverlaps getIMOverlapsImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mOverlapsImplPort"), IMOverlaps.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMOverlaps
     */
    @WebEndpoint(name = "I_mOverlapsImplPort")
    public IMOverlaps getIMOverlapsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mOverlapsImplPort"), IMOverlaps.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMOVERLAPSIMPLSERVICE_EXCEPTION!= null) {
            throw IMOVERLAPSIMPLSERVICE_EXCEPTION;
        }
        return IMOVERLAPSIMPLSERVICE_WSDL_LOCATION;
    }

}
