
package br.montage.stubs.mOverlaps;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mOverlaps", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMOverlaps {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mOverlaps.SetTblPortUses")
    @ResponseWrapper(localName = "setTblPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mOverlaps.SetTblPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mOverlaps/setTblPortUsesRequest", output = "http://be.montage.ufc.br/I_mOverlaps/setTblPortUsesResponse")
    public void setTblPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mOverlaps.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mOverlaps.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mOverlaps/goRequest", output = "http://be.montage.ufc.br/I_mOverlaps/goResponse")
    public void go();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTblPortProvides", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mOverlaps.GetTblPortProvides")
    @ResponseWrapper(localName = "getTblPortProvidesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mOverlaps.GetTblPortProvidesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mOverlaps/getTblPortProvidesRequest", output = "http://be.montage.ufc.br/I_mOverlaps/getTblPortProvidesResponse")
    public String getTblPortProvides();

}
