
package br.montage.stubs.mAdd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_mAddImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10004/mAdd?wsdl")
public class IMAddImplService
    extends Service
{

    private final static URL IMADDIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMADDIMPLSERVICE_EXCEPTION;
    private final static QName IMADDIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_mAddImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10004/mAdd?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMADDIMPLSERVICE_WSDL_LOCATION = url;
        IMADDIMPLSERVICE_EXCEPTION = e;
    }

    public IMAddImplService() {
        super(__getWsdlLocation(), IMADDIMPLSERVICE_QNAME);
    }

    public IMAddImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMADDIMPLSERVICE_QNAME, features);
    }

    public IMAddImplService(URL wsdlLocation) {
        super(wsdlLocation, IMADDIMPLSERVICE_QNAME);
    }

    public IMAddImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMADDIMPLSERVICE_QNAME, features);
    }

    public IMAddImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMAddImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMAdd
     */
    @WebEndpoint(name = "I_mAddImplPort")
    public IMAdd getIMAddImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mAddImplPort"), IMAdd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMAdd
     */
    @WebEndpoint(name = "I_mAddImplPort")
    public IMAdd getIMAddImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mAddImplPort"), IMAdd.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMADDIMPLSERVICE_EXCEPTION!= null) {
            throw IMADDIMPLSERVICE_EXCEPTION;
        }
        return IMADDIMPLSERVICE_WSDL_LOCATION;
    }

}
