
package br.montage.stubs.mImgtbl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mIgtbl", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMIgtbl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mImgtbl.SetDirPortUses")
    @ResponseWrapper(localName = "setDirPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mImgtbl.SetDirPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mIgtbl/setDirPortUsesRequest", output = "http://be.montage.ufc.br/I_mIgtbl/setDirPortUsesResponse")
    public void setDirPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mImgtbl.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mImgtbl.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mIgtbl/goRequest", output = "http://be.montage.ufc.br/I_mIgtbl/goResponse")
    public void go();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTblPortProvides", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mImgtbl.GetTblPortProvides")
    @ResponseWrapper(localName = "getTblPortProvidesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mImgtbl.GetTblPortProvidesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mIgtbl/getTblPortProvidesRequest", output = "http://be.montage.ufc.br/I_mIgtbl/getTblPortProvidesResponse")
    public String getTblPortProvides();

}
