
package br.ufc.mdcc.pargo.safe.port.predef.client.safeswl;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISAFeSWLPort", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ISAFeSWLPort {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getArchXMLLocation", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetArchXMLLocation")
    @ResponseWrapper(localName = "getArchXMLLocationResponse", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetArchXMLLocationResponse")
    @Action(input = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getArchXMLLocationRequest", output = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getArchXMLLocationResponse")
    public String getArchXMLLocation();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlowXMLLocation", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetFlowXMLLocation")
    @ResponseWrapper(localName = "getFlowXMLLocationResponse", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetFlowXMLLocationResponse")
    @Action(input = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getFlowXMLLocationRequest", output = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getFlowXMLLocationResponse")
    public String getFlowXMLLocation();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetNameResponse")
    @Action(input = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getNameRequest", output = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getNameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getId", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.port.predef.client.safeswl.GetIdResponse")
    @Action(input = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getIdRequest", output = "http://predef.port.safe.pargo.mdcc.ufc.br/ISAFeSWLPort/getIdResponse")
    public String getId();

}
