
package br.ufc.mdcc.pargo.safe.port.predef.client.safeswl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAFeSWLProvidesPortService", targetNamespace = "http://predef.port.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:8888/safeswl_provides?wsdl")
public class SAFeSWLProvidesPortService
    extends Service
{

    private final static URL SAFESWLPROVIDESPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SAFESWLPROVIDESPORTSERVICE_EXCEPTION;
    private final static QName SAFESWLPROVIDESPORTSERVICE_QNAME = new QName("http://predef.port.safe.pargo.mdcc.ufc.br/", "SAFeSWLProvidesPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/safeswl_provides?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAFESWLPROVIDESPORTSERVICE_WSDL_LOCATION = url;
        SAFESWLPROVIDESPORTSERVICE_EXCEPTION = e;
    }

    public SAFeSWLProvidesPortService() {
        super(__getWsdlLocation(), SAFESWLPROVIDESPORTSERVICE_QNAME);
    }

    public SAFeSWLProvidesPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAFESWLPROVIDESPORTSERVICE_QNAME, features);
    }

    public SAFeSWLProvidesPortService(URL wsdlLocation) {
        super(wsdlLocation, SAFESWLPROVIDESPORTSERVICE_QNAME);
    }

    public SAFeSWLProvidesPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAFESWLPROVIDESPORTSERVICE_QNAME, features);
    }

    public SAFeSWLProvidesPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAFeSWLProvidesPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISAFeSWLPort
     */
    @WebEndpoint(name = "SAFeSWLProvidesPortPort")
    public ISAFeSWLPort getSAFeSWLProvidesPortPort() {
        return super.getPort(new QName("http://predef.port.safe.pargo.mdcc.ufc.br/", "SAFeSWLProvidesPortPort"), ISAFeSWLPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISAFeSWLPort
     */
    @WebEndpoint(name = "SAFeSWLProvidesPortPort")
    public ISAFeSWLPort getSAFeSWLProvidesPortPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://predef.port.safe.pargo.mdcc.ufc.br/", "SAFeSWLProvidesPortPort"), ISAFeSWLPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAFESWLPROVIDESPORTSERVICE_EXCEPTION!= null) {
            throw SAFESWLPROVIDESPORTSERVICE_EXCEPTION;
        }
        return SAFESWLPROVIDESPORTSERVICE_WSDL_LOCATION;
    }

}
