
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.server.task;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceServerTaskImplService", targetNamespace = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10002/server-task?wsdl")
public class ServiceServerTaskImplService
    extends Service
{

    private final static URL SERVICESERVERTASKIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESERVERTASKIMPLSERVICE_EXCEPTION;
    private final static QName SERVICESERVERTASKIMPLSERVICE_QNAME = new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceServerTaskImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10002/server-task?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESERVERTASKIMPLSERVICE_WSDL_LOCATION = url;
        SERVICESERVERTASKIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceServerTaskImplService() {
        super(__getWsdlLocation(), SERVICESERVERTASKIMPLSERVICE_QNAME);
    }

    public ServiceServerTaskImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESERVERTASKIMPLSERVICE_QNAME, features);
    }

    public ServiceServerTaskImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESERVERTASKIMPLSERVICE_QNAME);
    }

    public ServiceServerTaskImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESERVERTASKIMPLSERVICE_QNAME, features);
    }

    public ServiceServerTaskImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceServerTaskImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceIServerTask
     */
    @WebEndpoint(name = "ServiceServerTaskImplPort")
    public ServiceIServerTask getServiceServerTaskImplPort() {
        return super.getPort(new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceServerTaskImplPort"), ServiceIServerTask.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceIServerTask
     */
    @WebEndpoint(name = "ServiceServerTaskImplPort")
    public ServiceIServerTask getServiceServerTaskImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.pc.backend.safe.pargo.mdcc.ufc.br/", "ServiceServerTaskImplPort"), ServiceIServerTask.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESERVERTASKIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICESERVERTASKIMPLSERVICE_EXCEPTION;
        }
        return SERVICESERVERTASKIMPLSERVICE_WSDL_LOCATION;
    }

}
