
package br.ufc.mdcc.pargo.safe.application.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHPCStormApplicationServer", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHPCStormApplicationServer {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setSAFeSWLArchSource", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.application.stub.SetSAFeSWLArchSource")
    @ResponseWrapper(localName = "setSAFeSWLArchSourceResponse", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.application.stub.SetSAFeSWLArchSourceResponse")
    @Action(input = "http://service.application.safe.pargo.mdcc.ufc.br/IHPCStormApplicationServer/setSAFeSWLArchSourceRequest", output = "http://service.application.safe.pargo.mdcc.ufc.br/IHPCStormApplicationServer/setSAFeSWLArchSourceResponse")
    public void setSAFeSWLArchSource(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setSAFeSWLFlowSource", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.application.stub.SetSAFeSWLFlowSource")
    @ResponseWrapper(localName = "setSAFeSWLFlowSourceResponse", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.application.stub.SetSAFeSWLFlowSourceResponse")
    @Action(input = "http://service.application.safe.pargo.mdcc.ufc.br/IHPCStormApplicationServer/setSAFeSWLFlowSourceRequest", output = "http://service.application.safe.pargo.mdcc.ufc.br/IHPCStormApplicationServer/setSAFeSWLFlowSourceResponse")
    public void setSAFeSWLFlowSource(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "run", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.application.stub.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://service.application.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.application.stub.RunResponse")
    @Action(input = "http://service.application.safe.pargo.mdcc.ufc.br/IHPCStormApplicationServer/runRequest", output = "http://service.application.safe.pargo.mdcc.ufc.br/IHPCStormApplicationServer/runResponse")
    public void run();

}
