
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.server.env;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceIServerEnv", targetNamespace = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceIServerEnv {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMsg", targetNamespace = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.server.env.GetMsg")
    @ResponseWrapper(localName = "getMsgResponse", targetNamespace = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.safe.sample.wspc.stubs.server.env.GetMsgResponse")
    @Action(input = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIServerEnv/getMsgRequest", output = "http://server.pc.backend.safe.pargo.mdcc.ufc.br/ServiceIServerEnv/getMsgResponse")
    public String getMsg();

}
