//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:25:49 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.ufc.mdcc.pargo.safe.grammar.flow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Workflow_QNAME = new QName("http://www.example.org/SAFE_workflow_V2", "workflow");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.ufc.mdcc.pargo.safe.grammar.flow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLSAFeAction }
     * 
     */
    public XMLSAFeAction createXMLSAFeAction() {
        return new XMLSAFeAction();
    }

    /**
     * Create an instance of {@link XMLSAFeOperation }
     * 
     */
    public XMLSAFeOperation createXMLSAFeOperation() {
        return new XMLSAFeOperation();
    }

    /**
     * Create an instance of {@link XMLSAFeOperation.RepeatOper }
     * 
     */
    public XMLSAFeOperation.RepeatOper createXMLSAFeOperationRepeatOper() {
        return new XMLSAFeOperation.RepeatOper();
    }

    /**
     * Create an instance of {@link XMLSAFeOperation.ChoiceOper }
     * 
     */
    public XMLSAFeOperation.ChoiceOper createXMLSAFeOperationChoiceOper() {
        return new XMLSAFeOperation.ChoiceOper();
    }

    /**
     * Create an instance of {@link XMLSAFeCompOper }
     * 
     */
    public XMLSAFeCompOper createXMLSAFeCompOper() {
        return new XMLSAFeCompOper();
    }

    /**
     * Create an instance of {@link XMLSAFeBase }
     * 
     */
    public XMLSAFeBase createXMLSAFeBase() {
        return new XMLSAFeBase();
    }

    /**
     * Create an instance of {@link XMLSAFePrimOper }
     * 
     */
    public XMLSAFePrimOper createXMLSAFePrimOper() {
        return new XMLSAFePrimOper();
    }

    /**
     * Create an instance of {@link XMLSAFeAction.Resolve }
     * 
     */
    public XMLSAFeAction.Resolve createXMLSAFeActionResolve() {
        return new XMLSAFeAction.Resolve();
    }

    /**
     * Create an instance of {@link XMLSAFeAction.Instantiate }
     * 
     */
    public XMLSAFeAction.Instantiate createXMLSAFeActionInstantiate() {
        return new XMLSAFeAction.Instantiate();
    }

    /**
     * Create an instance of {@link XMLSAFeAction.Compute }
     * 
     */
    public XMLSAFeAction.Compute createXMLSAFeActionCompute() {
        return new XMLSAFeAction.Compute();
    }

    /**
     * Create an instance of {@link XMLSAFeOperation.RepeatOper.Continue }
     * 
     */
    public XMLSAFeOperation.RepeatOper.Continue createXMLSAFeOperationRepeatOperContinue() {
        return new XMLSAFeOperation.RepeatOper.Continue();
    }

    /**
     * Create an instance of {@link XMLSAFeOperation.RepeatOper.Stop }
     * 
     */
    public XMLSAFeOperation.RepeatOper.Stop createXMLSAFeOperationRepeatOperStop() {
        return new XMLSAFeOperation.RepeatOper.Stop();
    }

    /**
     * Create an instance of {@link XMLSAFeOperation.ChoiceOper.Alt }
     * 
     */
    public XMLSAFeOperation.ChoiceOper.Alt createXMLSAFeOperationChoiceOperAlt() {
        return new XMLSAFeOperation.ChoiceOper.Alt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLSAFeOperation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/SAFE_workflow_V2", name = "workflow")
    public JAXBElement<XMLSAFeOperation> createWorkflow(XMLSAFeOperation value) {
        return new JAXBElement<XMLSAFeOperation>(_Workflow_QNAME, XMLSAFeOperation.class, null, value);
    }

}
