//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:53:13 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/SAFe_workflow_V3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.ufc.mdcc.pargo.safe.grammar.flow;
