package br.ufc.mdcc.pargo.safe.grammar.flow;

public enum SAFeOrchestrationOperation {

	WORKFLOW,
	SEQUENCEOPER, PARALLELOPER, CHOICEOPER, REPEATOPER,
	STARTOPER, WAITOPER, CANCELOPER, INVOKEOPER, SKIPOPER,
	ACTION, ID,
	OPERATION,
	ALT,
	REPEAT, CONTINUE,STOP,
	RESOLVE, INSTANTIATE, COMPUTE,
	ACTIONID
}
