//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:25:49 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XML_SAFe_Action complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XML_SAFe_Action">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *       &lt;choice>
 *         &lt;element name="resolve">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                 &lt;attribute name="component_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="instantiate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                 &lt;attribute name="component_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="compute">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                 &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XML_SAFe_Action", propOrder = {
    "resolve",
    "instantiate",
    "compute"
})
public class XMLSAFeAction
    extends XMLSAFeBase
{

    protected XMLSAFeAction.Resolve resolve;
    protected XMLSAFeAction.Instantiate instantiate;
    protected XMLSAFeAction.Compute compute;

    /**
     * Gets the value of the resolve property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction.Resolve }
     *     
     */
    public XMLSAFeAction.Resolve getResolve() {
        return resolve;
    }

    /**
     * Sets the value of the resolve property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction.Resolve }
     *     
     */
    public void setResolve(XMLSAFeAction.Resolve value) {
        this.resolve = value;
    }

    /**
     * Gets the value of the instantiate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction.Instantiate }
     *     
     */
    public XMLSAFeAction.Instantiate getInstantiate() {
        return instantiate;
    }

    /**
     * Sets the value of the instantiate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction.Instantiate }
     *     
     */
    public void setInstantiate(XMLSAFeAction.Instantiate value) {
        this.instantiate = value;
    }

    /**
     * Gets the value of the compute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction.Compute }
     *     
     */
    public XMLSAFeAction.Compute getCompute() {
        return compute;
    }

    /**
     * Sets the value of the compute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction.Compute }
     *     
     */
    public void setCompute(XMLSAFeAction.Compute value) {
        this.compute = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *       &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Compute
        extends XMLSAFeBase
    {

        @XmlAttribute(name = "action_id")
        protected String actionId;

        /**
         * Gets the value of the actionId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActionId() {
            return actionId;
        }

        /**
         * Sets the value of the actionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionId(String value) {
            this.actionId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *       &lt;attribute name="component_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Instantiate
        extends XMLSAFeBase
    {

        @XmlAttribute(name = "component_id")
        protected String componentId;

        /**
         * Gets the value of the componentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComponentId() {
            return componentId;
        }

        /**
         * Sets the value of the componentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComponentId(String value) {
            this.componentId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *       &lt;attribute name="component_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Resolve
        extends XMLSAFeBase
    {

        @XmlAttribute(name = "component_id")
        protected String componentId;

        /**
         * Gets the value of the componentId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getComponentId() {
            return componentId;
        }

        /**
         * Sets the value of the componentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setComponentId(String value) {
            this.componentId = value;
        }

    }

}
