//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:25:49 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XML_SAFe_Operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XML_SAFe_Operation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *       &lt;choice>
 *         &lt;element name="start_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="wait_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="cancel_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="invoke_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="skip_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base"/>
 *         &lt;element name="sequence_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Comp_Oper"/>
 *         &lt;element name="parallel_oper" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Comp_Oper"/>
 *         &lt;element name="choice_oper">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                 &lt;sequence>
 *                   &lt;element name="alt" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                           &lt;sequence>
 *                             &lt;element name="action_id" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="operation" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Operation" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="repeat_oper">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                 &lt;sequence>
 *                   &lt;element name="repeat" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Operation"/>
 *                   &lt;element name="continue">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                           &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="stop">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *                           &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XML_SAFe_Operation", propOrder = {
    "startOper",
    "waitOper",
    "cancelOper",
    "invokeOper",
    "skipOper",
    "sequenceOper",
    "parallelOper",
    "choiceOper",
    "repeatOper"
})
public class XMLSAFeOperation
    extends XMLSAFeBase
{

    @XmlElement(name = "start_oper")
    protected XMLSAFePrimOper startOper;
    @XmlElement(name = "wait_oper")
    protected XMLSAFePrimOper waitOper;
    @XmlElement(name = "cancel_oper")
    protected XMLSAFePrimOper cancelOper;
    @XmlElement(name = "invoke_oper")
    protected XMLSAFePrimOper invokeOper;
    @XmlElement(name = "skip_oper")
    protected XMLSAFeBase skipOper;
    @XmlElement(name = "sequence_oper")
    protected XMLSAFeCompOper sequenceOper;
    @XmlElement(name = "parallel_oper")
    protected XMLSAFeCompOper parallelOper;
    @XmlElement(name = "choice_oper")
    protected XMLSAFeOperation.ChoiceOper choiceOper;
    @XmlElement(name = "repeat_oper")
    protected XMLSAFeOperation.RepeatOper repeatOper;

    /**
     * Gets the value of the startOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getStartOper() {
        return startOper;
    }

    /**
     * Sets the value of the startOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setStartOper(XMLSAFePrimOper value) {
        this.startOper = value;
    }

    /**
     * Gets the value of the waitOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getWaitOper() {
        return waitOper;
    }

    /**
     * Sets the value of the waitOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setWaitOper(XMLSAFePrimOper value) {
        this.waitOper = value;
    }

    /**
     * Gets the value of the cancelOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getCancelOper() {
        return cancelOper;
    }

    /**
     * Sets the value of the cancelOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setCancelOper(XMLSAFePrimOper value) {
        this.cancelOper = value;
    }

    /**
     * Gets the value of the invokeOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getInvokeOper() {
        return invokeOper;
    }

    /**
     * Sets the value of the invokeOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setInvokeOper(XMLSAFePrimOper value) {
        this.invokeOper = value;
    }

    /**
     * Gets the value of the skipOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getSkipOper() {
        return skipOper;
    }

    /**
     * Sets the value of the skipOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setSkipOper(XMLSAFeBase value) {
        this.skipOper = value;
    }

    /**
     * Gets the value of the sequenceOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public XMLSAFeCompOper getSequenceOper() {
        return sequenceOper;
    }

    /**
     * Sets the value of the sequenceOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public void setSequenceOper(XMLSAFeCompOper value) {
        this.sequenceOper = value;
    }

    /**
     * Gets the value of the parallelOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public XMLSAFeCompOper getParallelOper() {
        return parallelOper;
    }

    /**
     * Sets the value of the parallelOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public void setParallelOper(XMLSAFeCompOper value) {
        this.parallelOper = value;
    }

    /**
     * Gets the value of the choiceOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeOperation.ChoiceOper }
     *     
     */
    public XMLSAFeOperation.ChoiceOper getChoiceOper() {
        return choiceOper;
    }

    /**
     * Sets the value of the choiceOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeOperation.ChoiceOper }
     *     
     */
    public void setChoiceOper(XMLSAFeOperation.ChoiceOper value) {
        this.choiceOper = value;
    }

    /**
     * Gets the value of the repeatOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeOperation.RepeatOper }
     *     
     */
    public XMLSAFeOperation.RepeatOper getRepeatOper() {
        return repeatOper;
    }

    /**
     * Sets the value of the repeatOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeOperation.RepeatOper }
     *     
     */
    public void setRepeatOper(XMLSAFeOperation.RepeatOper value) {
        this.repeatOper = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *       &lt;sequence>
     *         &lt;element name="alt" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *                 &lt;sequence>
     *                   &lt;element name="action_id" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="operation" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Operation" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alt"
    })
    public static class ChoiceOper
        extends XMLSAFeBase
    {

        @XmlElement(required = true)
        protected List<XMLSAFeOperation.ChoiceOper.Alt> alt;

        /**
         * Gets the value of the alt property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the alt property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAlt().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XMLSAFeOperation.ChoiceOper.Alt }
         * 
         * 
         */
        public List<XMLSAFeOperation.ChoiceOper.Alt> getAlt() {
            if (alt == null) {
                alt = new ArrayList<XMLSAFeOperation.ChoiceOper.Alt>();
            }
            return this.alt;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
         *       &lt;sequence>
         *         &lt;element name="action_id" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="operation" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Operation" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "actionId",
            "operation"
        })
        public static class Alt
            extends XMLSAFeBase
        {

            @XmlElement(name = "action_id")
            protected List<XMLSAFeBase> actionId;
            protected XMLSAFeOperation operation;

            /**
             * Gets the value of the actionId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the actionId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getActionId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link XMLSAFeBase }
             * 
             * 
             */
            public List<XMLSAFeBase> getActionId() {
                if (actionId == null) {
                    actionId = new ArrayList<XMLSAFeBase>();
                }
                return this.actionId;
            }

            /**
             * Gets the value of the operation property.
             * 
             * @return
             *     possible object is
             *     {@link XMLSAFeOperation }
             *     
             */
            public XMLSAFeOperation getOperation() {
                return operation;
            }

            /**
             * Sets the value of the operation property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLSAFeOperation }
             *     
             */
            public void setOperation(XMLSAFeOperation value) {
                this.operation = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *       &lt;sequence>
     *         &lt;element name="repeat" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Operation"/>
     *         &lt;element name="continue">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *                 &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="stop">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
     *                 &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "repeat",
        "_continue",
        "stop"
    })
    public static class RepeatOper
        extends XMLSAFeBase
    {

        @XmlElement(required = true)
        protected XMLSAFeOperation repeat;
        @XmlElement(name = "continue", required = true)
        protected XMLSAFeOperation.RepeatOper.Continue _continue;
        @XmlElement(required = true)
        protected XMLSAFeOperation.RepeatOper.Stop stop;

        /**
         * Gets the value of the repeat property.
         * 
         * @return
         *     possible object is
         *     {@link XMLSAFeOperation }
         *     
         */
        public XMLSAFeOperation getRepeat() {
            return repeat;
        }

        /**
         * Sets the value of the repeat property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLSAFeOperation }
         *     
         */
        public void setRepeat(XMLSAFeOperation value) {
            this.repeat = value;
        }

        /**
         * Gets the value of the continue property.
         * 
         * @return
         *     possible object is
         *     {@link XMLSAFeOperation.RepeatOper.Continue }
         *     
         */
        public XMLSAFeOperation.RepeatOper.Continue getContinue() {
            return _continue;
        }

        /**
         * Sets the value of the continue property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLSAFeOperation.RepeatOper.Continue }
         *     
         */
        public void setContinue(XMLSAFeOperation.RepeatOper.Continue value) {
            this._continue = value;
        }

        /**
         * Gets the value of the stop property.
         * 
         * @return
         *     possible object is
         *     {@link XMLSAFeOperation.RepeatOper.Stop }
         *     
         */
        public XMLSAFeOperation.RepeatOper.Stop getStop() {
            return stop;
        }

        /**
         * Sets the value of the stop property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLSAFeOperation.RepeatOper.Stop }
         *     
         */
        public void setStop(XMLSAFeOperation.RepeatOper.Stop value) {
            this.stop = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
         *       &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Continue
            extends XMLSAFeBase
        {

            @XmlAttribute(name = "action_id")
            protected String actionId;

            /**
             * Gets the value of the actionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActionId() {
                return actionId;
            }

            /**
             * Sets the value of the actionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionId(String value) {
                this.actionId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
         *       &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Stop
            extends XMLSAFeBase
        {

            @XmlAttribute(name = "action_id")
            protected String actionId;

            /**
             * Gets the value of the actionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActionId() {
                return actionId;
            }

            /**
             * Sets the value of the actionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionId(String value) {
                this.actionId = value;
            }

        }

    }

}
