//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.09 at 05:25:49 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XML_SAFe_Prim_Oper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XML_SAFe_Prim_Oper">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base">
 *       &lt;sequence>
 *         &lt;element name="action" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Action"/>
 *         &lt;element name="id" type="{http://www.example.org/SAFE_workflow_V2}XML_SAFe_Base"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XML_SAFe_Prim_Oper", propOrder = {
    "action",
    "id"
})
public class XMLSAFePrimOper
    extends XMLSAFeBase
{

    @XmlElement(required = true)
    protected XMLSAFeAction action;
    @XmlElement(required = true)
    protected XMLSAFeBase id;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction }
     *     
     */
    public XMLSAFeAction getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction }
     *     
     */
    public void setAction(XMLSAFeAction value) {
        this.action = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setId(XMLSAFeBase value) {
        this.id = value;
    }

}
