//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:53:13 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XML_SAFe_Prim_Oper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XML_SAFe_Prim_Oper">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
 *       &lt;sequence>
 *         &lt;element name="action" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Action"/>
 *       &lt;/sequence>
 *       &lt;attribute name="handle_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XML_SAFe_Prim_Oper", propOrder = {
    "action"
})
public class XMLSAFePrimOper
    extends XMLSAFeBase
{

    @XmlElement(required = true)
    protected XMLSAFeAction action;
    @XmlAttribute(name = "handle_id")
    protected String handleId;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction }
     *     
     */
    public XMLSAFeAction getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction }
     *     
     */
    public void setAction(XMLSAFeAction value) {
        this.action = value;
    }

    /**
     * Gets the value of the handleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandleId() {
        return handleId;
    }

    /**
     * Sets the value of the handleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandleId(String value) {
        this.handleId = value;
    }

}
