//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.06 at 05:53:13 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XML_SAFe_Operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XML_SAFe_Operation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
 *       &lt;choice>
 *         &lt;element name="skip_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base"/>
 *         &lt;element name="break_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base"/>
 *         &lt;element name="continue" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base"/>
 *         &lt;element name="start_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="wait_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="cancel_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="invoke_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Action"/>
 *         &lt;element name="sequence_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Comp_Oper"/>
 *         &lt;element name="parallel_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Comp_Oper"/>
 *         &lt;element name="choice_oper">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
 *                 &lt;sequence>
 *                   &lt;element name="select_operation" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
 *                           &lt;sequence>
 *                             &lt;element name="operation" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Operation"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="iterate_oper" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Operation"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XML_SAFe_Operation", propOrder = {
    "skipOper",
    "breakOper",
    "_continue",
    "startOper",
    "waitOper",
    "cancelOper",
    "invokeOper",
    "sequenceOper",
    "parallelOper",
    "choiceOper",
    "iterateOper"
})
public class XMLSAFeOperation
    extends XMLSAFeBase
{

    @XmlElement(name = "skip_oper")
    protected XMLSAFeBase skipOper;
    @XmlElement(name = "break_oper")
    protected XMLSAFeBase breakOper;
    @XmlElement(name = "continue")
    protected XMLSAFeBase _continue;
    @XmlElement(name = "start_oper")
    protected XMLSAFePrimOper startOper;
    @XmlElement(name = "wait_oper")
    protected XMLSAFePrimOper waitOper;
    @XmlElement(name = "cancel_oper")
    protected XMLSAFePrimOper cancelOper;
    @XmlElement(name = "invoke_oper")
    protected XMLSAFeAction invokeOper;
    @XmlElement(name = "sequence_oper")
    protected XMLSAFeCompOper sequenceOper;
    @XmlElement(name = "parallel_oper")
    protected XMLSAFeCompOper parallelOper;
    @XmlElement(name = "choice_oper")
    protected XMLSAFeOperation.ChoiceOper choiceOper;
    @XmlElement(name = "iterate_oper")
    protected XMLSAFeOperation iterateOper;

    /**
     * Gets the value of the skipOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getSkipOper() {
        return skipOper;
    }

    /**
     * Sets the value of the skipOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setSkipOper(XMLSAFeBase value) {
        this.skipOper = value;
    }

    /**
     * Gets the value of the breakOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getBreakOper() {
        return breakOper;
    }

    /**
     * Sets the value of the breakOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setBreakOper(XMLSAFeBase value) {
        this.breakOper = value;
    }

    /**
     * Gets the value of the continue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getContinue() {
        return _continue;
    }

    /**
     * Sets the value of the continue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setContinue(XMLSAFeBase value) {
        this._continue = value;
    }

    /**
     * Gets the value of the startOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getStartOper() {
        return startOper;
    }

    /**
     * Sets the value of the startOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setStartOper(XMLSAFePrimOper value) {
        this.startOper = value;
    }

    /**
     * Gets the value of the waitOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getWaitOper() {
        return waitOper;
    }

    /**
     * Sets the value of the waitOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setWaitOper(XMLSAFePrimOper value) {
        this.waitOper = value;
    }

    /**
     * Gets the value of the cancelOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getCancelOper() {
        return cancelOper;
    }

    /**
     * Sets the value of the cancelOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setCancelOper(XMLSAFePrimOper value) {
        this.cancelOper = value;
    }

    /**
     * Gets the value of the invokeOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction }
     *     
     */
    public XMLSAFeAction getInvokeOper() {
        return invokeOper;
    }

    /**
     * Sets the value of the invokeOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction }
     *     
     */
    public void setInvokeOper(XMLSAFeAction value) {
        this.invokeOper = value;
    }

    /**
     * Gets the value of the sequenceOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public XMLSAFeCompOper getSequenceOper() {
        return sequenceOper;
    }

    /**
     * Sets the value of the sequenceOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public void setSequenceOper(XMLSAFeCompOper value) {
        this.sequenceOper = value;
    }

    /**
     * Gets the value of the parallelOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public XMLSAFeCompOper getParallelOper() {
        return parallelOper;
    }

    /**
     * Sets the value of the parallelOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public void setParallelOper(XMLSAFeCompOper value) {
        this.parallelOper = value;
    }

    /**
     * Gets the value of the choiceOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeOperation.ChoiceOper }
     *     
     */
    public XMLSAFeOperation.ChoiceOper getChoiceOper() {
        return choiceOper;
    }

    /**
     * Sets the value of the choiceOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeOperation.ChoiceOper }
     *     
     */
    public void setChoiceOper(XMLSAFeOperation.ChoiceOper value) {
        this.choiceOper = value;
    }

    /**
     * Gets the value of the iterateOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeOperation }
     *     
     */
    public XMLSAFeOperation getIterateOper() {
        return iterateOper;
    }

    /**
     * Sets the value of the iterateOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeOperation }
     *     
     */
    public void setIterateOper(XMLSAFeOperation value) {
        this.iterateOper = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
     *       &lt;sequence>
     *         &lt;element name="select_operation" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
     *                 &lt;sequence>
     *                   &lt;element name="operation" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Operation"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "selectOperation"
    })
    public static class ChoiceOper
        extends XMLSAFeBase
    {

        @XmlElement(name = "select_operation", required = true)
        protected List<XMLSAFeOperation.ChoiceOper.SelectOperation> selectOperation;

        /**
         * Gets the value of the selectOperation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the selectOperation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSelectOperation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XMLSAFeOperation.ChoiceOper.SelectOperation }
         * 
         * 
         */
        public List<XMLSAFeOperation.ChoiceOper.SelectOperation> getSelectOperation() {
            if (selectOperation == null) {
                selectOperation = new ArrayList<XMLSAFeOperation.ChoiceOper.SelectOperation>();
            }
            return this.selectOperation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Base">
         *       &lt;sequence>
         *         &lt;element name="operation" type="{http://www.example.org/SAFe_workflow_V3}XML_SAFe_Operation"/>
         *       &lt;/sequence>
         *       &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "operation"
        })
        public static class SelectOperation
            extends XMLSAFeBase
        {

            @XmlElement(required = true)
            protected XMLSAFeOperation operation;
            @XmlAttribute(name = "action_id")
            protected String actionId;

            /**
             * Gets the value of the operation property.
             * 
             * @return
             *     possible object is
             *     {@link XMLSAFeOperation }
             *     
             */
            public XMLSAFeOperation getOperation() {
                return operation;
            }

            /**
             * Sets the value of the operation property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLSAFeOperation }
             *     
             */
            public void setOperation(XMLSAFeOperation value) {
                this.operation = value;
            }

            /**
             * Gets the value of the actionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActionId() {
                return actionId;
            }

            /**
             * Sets the value of the actionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionId(String value) {
                this.actionId = value;
            }

        }

    }

}
