//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.26 at 04:32:39 PM BRT 
//


package br.ufc.mdcc.pargo.safe.grammar.flow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XML_SAFe_Operation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XML_SAFe_Operation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Base">
 *       &lt;choice>
 *         &lt;element name="skip_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Base"/>
 *         &lt;element name="break_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Base"/>
 *         &lt;element name="continue_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Base"/>
 *         &lt;element name="start_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="wait_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="cancel_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Prim_Oper"/>
 *         &lt;element name="invoke_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Action"/>
 *         &lt;element name="sequence_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Comp_Oper"/>
 *         &lt;element name="parallel_oper" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Comp_Oper"/>
 *         &lt;element name="choice_oper" type="{http://www.example.org/SAFe_workflow_V4}choice_operComplexType"/>
 *         &lt;element name="iterate_oper">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Base">
 *                 &lt;sequence>
 *                   &lt;element name="operation" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Operation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XML_SAFe_Operation", propOrder = {
    "skipOper",
    "breakOper",
    "continueOper",
    "startOper",
    "waitOper",
    "cancelOper",
    "invokeOper",
    "sequenceOper",
    "parallelOper",
    "choiceOper",
    "iterateOper"
})
public class XMLSAFeOperation
    extends XMLSAFeBase
{

    @XmlElement(name = "skip_oper")
    protected XMLSAFeBase skipOper;
    @XmlElement(name = "break_oper")
    protected XMLSAFeBase breakOper;
    @XmlElement(name = "continue_oper")
    protected XMLSAFeBase continueOper;
    @XmlElement(name = "start_oper")
    protected XMLSAFePrimOper startOper;
    @XmlElement(name = "wait_oper")
    protected XMLSAFePrimOper waitOper;
    @XmlElement(name = "cancel_oper")
    protected XMLSAFePrimOper cancelOper;
    @XmlElement(name = "invoke_oper")
    protected XMLSAFeAction invokeOper;
    @XmlElement(name = "sequence_oper")
    protected XMLSAFeCompOper sequenceOper;
    @XmlElement(name = "parallel_oper")
    protected XMLSAFeCompOper parallelOper;
    @XmlElement(name = "choice_oper")
    protected ChoiceOperComplexType choiceOper;
    @XmlElement(name = "iterate_oper")
    protected XMLSAFeOperation.IterateOper iterateOper;

    /**
     * Gets the value of the skipOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getSkipOper() {
        return skipOper;
    }

    /**
     * Sets the value of the skipOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setSkipOper(XMLSAFeBase value) {
        this.skipOper = value;
    }

    /**
     * Gets the value of the breakOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getBreakOper() {
        return breakOper;
    }

    /**
     * Sets the value of the breakOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setBreakOper(XMLSAFeBase value) {
        this.breakOper = value;
    }

    /**
     * Gets the value of the continueOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeBase }
     *     
     */
    public XMLSAFeBase getContinueOper() {
        return continueOper;
    }

    /**
     * Sets the value of the continueOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeBase }
     *     
     */
    public void setContinueOper(XMLSAFeBase value) {
        this.continueOper = value;
    }

    /**
     * Gets the value of the startOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getStartOper() {
        return startOper;
    }

    /**
     * Sets the value of the startOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setStartOper(XMLSAFePrimOper value) {
        this.startOper = value;
    }

    /**
     * Gets the value of the waitOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getWaitOper() {
        return waitOper;
    }

    /**
     * Sets the value of the waitOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setWaitOper(XMLSAFePrimOper value) {
        this.waitOper = value;
    }

    /**
     * Gets the value of the cancelOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public XMLSAFePrimOper getCancelOper() {
        return cancelOper;
    }

    /**
     * Sets the value of the cancelOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFePrimOper }
     *     
     */
    public void setCancelOper(XMLSAFePrimOper value) {
        this.cancelOper = value;
    }

    /**
     * Gets the value of the invokeOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeAction }
     *     
     */
    public XMLSAFeAction getInvokeOper() {
        return invokeOper;
    }

    /**
     * Sets the value of the invokeOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeAction }
     *     
     */
    public void setInvokeOper(XMLSAFeAction value) {
        this.invokeOper = value;
    }

    /**
     * Gets the value of the sequenceOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public XMLSAFeCompOper getSequenceOper() {
        return sequenceOper;
    }

    /**
     * Sets the value of the sequenceOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public void setSequenceOper(XMLSAFeCompOper value) {
        this.sequenceOper = value;
    }

    /**
     * Gets the value of the parallelOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public XMLSAFeCompOper getParallelOper() {
        return parallelOper;
    }

    /**
     * Sets the value of the parallelOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeCompOper }
     *     
     */
    public void setParallelOper(XMLSAFeCompOper value) {
        this.parallelOper = value;
    }

    /**
     * Gets the value of the choiceOper property.
     * 
     * @return
     *     possible object is
     *     {@link ChoiceOperComplexType }
     *     
     */
    public ChoiceOperComplexType getChoiceOper() {
        return choiceOper;
    }

    /**
     * Sets the value of the choiceOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoiceOperComplexType }
     *     
     */
    public void setChoiceOper(ChoiceOperComplexType value) {
        this.choiceOper = value;
    }

    /**
     * Gets the value of the iterateOper property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSAFeOperation.IterateOper }
     *     
     */
    public XMLSAFeOperation.IterateOper getIterateOper() {
        return iterateOper;
    }

    /**
     * Sets the value of the iterateOper property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSAFeOperation.IterateOper }
     *     
     */
    public void setIterateOper(XMLSAFeOperation.IterateOper value) {
        this.iterateOper = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Base">
     *       &lt;sequence>
     *         &lt;element name="operation" type="{http://www.example.org/SAFe_workflow_V4}XML_SAFe_Operation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operation"
    })
    public static class IterateOper
        extends XMLSAFeBase
    {

        @XmlElement(required = true)
        protected List<XMLSAFeOperation> operation;
        @XmlAttribute(name = "max")
        protected Integer max;

        /**
         * Gets the value of the operation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XMLSAFeOperation }
         * 
         * 
         */
        public List<XMLSAFeOperation> getOperation() {
            if (operation == null) {
                operation = new ArrayList<XMLSAFeOperation>();
            }
            return this.operation;
        }

        /**
         * Gets the value of the max property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMax(Integer value) {
            this.max = value;
        }

    }

}
