
package br.ufc.mdcc.pargo.backend.app.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ApplicationEnvPortImplService", targetNamespace = "http://services.application.sample.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10010/app-port?wsdl")
public class ApplicationEnvPortImplService
    extends Service
{

    private final static URL APPLICATIONENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPLICATIONENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName APPLICATIONENVPORTIMPLSERVICE_QNAME = new QName("http://services.application.sample.safe.pargo.mdcc.ufc.br/", "ApplicationEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10010/app-port?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPLICATIONENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        APPLICATIONENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public ApplicationEnvPortImplService() {
        super(__getWsdlLocation(), APPLICATIONENVPORTIMPLSERVICE_QNAME);
    }

    public ApplicationEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPLICATIONENVPORTIMPLSERVICE_QNAME, features);
    }

    public ApplicationEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, APPLICATIONENVPORTIMPLSERVICE_QNAME);
    }

    public ApplicationEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPLICATIONENVPORTIMPLSERVICE_QNAME, features);
    }

    public ApplicationEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ApplicationEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IApplicationEnvPort
     */
    @WebEndpoint(name = "ApplicationEnvPortImplPort")
    public IApplicationEnvPort getApplicationEnvPortImplPort() {
        return super.getPort(new QName("http://services.application.sample.safe.pargo.mdcc.ufc.br/", "ApplicationEnvPortImplPort"), IApplicationEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IApplicationEnvPort
     */
    @WebEndpoint(name = "ApplicationEnvPortImplPort")
    public IApplicationEnvPort getApplicationEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.application.sample.safe.pargo.mdcc.ufc.br/", "ApplicationEnvPortImplPort"), IApplicationEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPLICATIONENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw APPLICATIONENVPORTIMPLSERVICE_EXCEPTION;
        }
        return APPLICATIONENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
