
package br.ufc.mdcc.pargo.backend.app.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IApplicationEnvPort", targetNamespace = "http://services.application.sample.safe.pargo.mdcc.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IApplicationEnvPort {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "requestMessage", targetNamespace = "http://services.application.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.app.stubs.RequestMessage")
    @ResponseWrapper(localName = "requestMessageResponse", targetNamespace = "http://services.application.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.app.stubs.RequestMessageResponse")
    @Action(input = "http://services.application.sample.safe.pargo.mdcc.ufc.br/IApplicationEnvPort/requestMessageRequest", output = "http://services.application.sample.safe.pargo.mdcc.ufc.br/IApplicationEnvPort/requestMessageResponse")
    public void requestMessage();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "receiveMessage", targetNamespace = "http://services.application.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.app.stubs.ReceiveMessage")
    @ResponseWrapper(localName = "receiveMessageResponse", targetNamespace = "http://services.application.sample.safe.pargo.mdcc.ufc.br/", className = "br.ufc.mdcc.pargo.backend.app.stubs.ReceiveMessageResponse")
    @Action(input = "http://services.application.sample.safe.pargo.mdcc.ufc.br/IApplicationEnvPort/receiveMessageRequest", output = "http://services.application.sample.safe.pargo.mdcc.ufc.br/IApplicationEnvPort/receiveMessageResponse")
    public void receiveMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
