package br.ufc.mdcc.pargo.safe.grammar.flow;

public enum SAFeOrchestrationOperation {

	WORKFLOW,
	SEQUENCE, PARALLEL, CHOICE, REPEAT,
	START, WAIT, CANCEL, INVOKE, SKIP, BREAK, ITERATE, CONTINUE,
	ACTION, ID,
	OPERATION,
	RESOLVE, INSTANTIATE, COMPUTE, DEPLOY,
	ACTIONID,
	SELECT
}
