
package br.ufc.mdcc.pargo.safe.sample.wspc.stubs.client.oper;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSIClientProducerOperationPortImplService", targetNamespace = "http://client.pc.backend.safe.pargo.mdcc.ufc.br/", wsdlLocation = "http://localhost:10005/client-operation?wsdl")
public class WSIClientProducerOperationPortImplService
    extends Service
{

    private final static URL WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_EXCEPTION;
    private final static QName WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_QNAME = new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIClientProducerOperationPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10005/client-operation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_WSDL_LOCATION = url;
        WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_EXCEPTION = e;
    }

    public WSIClientProducerOperationPortImplService() {
        super(__getWsdlLocation(), WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_QNAME);
    }

    public WSIClientProducerOperationPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_QNAME, features);
    }

    public WSIClientProducerOperationPortImplService(URL wsdlLocation) {
        super(wsdlLocation, WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_QNAME);
    }

    public WSIClientProducerOperationPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_QNAME, features);
    }

    public WSIClientProducerOperationPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSIClientProducerOperationPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSIClientProducerOperationPort
     */
    @WebEndpoint(name = "WSIClientProducerOperationPortImplPort")
    public WSIClientProducerOperationPort getWSIClientProducerOperationPortImplPort() {
        return super.getPort(new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIClientProducerOperationPortImplPort"), WSIClientProducerOperationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSIClientProducerOperationPort
     */
    @WebEndpoint(name = "WSIClientProducerOperationPortImplPort")
    public WSIClientProducerOperationPort getWSIClientProducerOperationPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.pc.backend.safe.pargo.mdcc.ufc.br/", "WSIClientProducerOperationPortImplPort"), WSIClientProducerOperationPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_EXCEPTION!= null) {
            throw WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_EXCEPTION;
        }
        return WSICLIENTPRODUCEROPERATIONPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
