
package br.ufc.m101.stubs.mdiffexec.env;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MDiffExecEnvPort", targetNamespace = "http://mdiffexec.component.m101.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MDiffExecEnvPort {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setParams", targetNamespace = "http://mdiffexec.component.m101.ufc.br/", className = "br.ufc.m101.stubs.mdiffexec.env.SetParams")
    @ResponseWrapper(localName = "setParamsResponse", targetNamespace = "http://mdiffexec.component.m101.ufc.br/", className = "br.ufc.m101.stubs.mdiffexec.env.SetParamsResponse")
    @Action(input = "http://mdiffexec.component.m101.ufc.br/MDiffExecEnvPort/setParamsRequest", output = "http://mdiffexec.component.m101.ufc.br/MDiffExecEnvPort/setParamsResponse")
    public void setParams(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
