
package br.ufc.m101.stubs.mdiffexec.env;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MDiffExecEnvPortImplService", targetNamespace = "http://mdiffexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11406/mdiffexec-env?wsdl")
public class MDiffExecEnvPortImplService
    extends Service
{

    private final static URL MDIFFEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MDIFFEXECENVPORTIMPLSERVICE_EXCEPTION;
    private final static QName MDIFFEXECENVPORTIMPLSERVICE_QNAME = new QName("http://mdiffexec.component.m101.ufc.br/", "MDiffExecEnvPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11406/mdiffexec-env?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDIFFEXECENVPORTIMPLSERVICE_WSDL_LOCATION = url;
        MDIFFEXECENVPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MDiffExecEnvPortImplService() {
        super(__getWsdlLocation(), MDIFFEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MDiffExecEnvPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDIFFEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MDiffExecEnvPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MDIFFEXECENVPORTIMPLSERVICE_QNAME);
    }

    public MDiffExecEnvPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDIFFEXECENVPORTIMPLSERVICE_QNAME, features);
    }

    public MDiffExecEnvPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDiffExecEnvPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MDiffExecEnvPort
     */
    @WebEndpoint(name = "MDiffExecEnvPortImplPort")
    public MDiffExecEnvPort getMDiffExecEnvPortImplPort() {
        return super.getPort(new QName("http://mdiffexec.component.m101.ufc.br/", "MDiffExecEnvPortImplPort"), MDiffExecEnvPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDiffExecEnvPort
     */
    @WebEndpoint(name = "MDiffExecEnvPortImplPort")
    public MDiffExecEnvPort getMDiffExecEnvPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdiffexec.component.m101.ufc.br/", "MDiffExecEnvPortImplPort"), MDiffExecEnvPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDIFFEXECENVPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MDIFFEXECENVPORTIMPLSERVICE_EXCEPTION;
        }
        return MDIFFEXECENVPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
