
package br.montage.stubs.mArchiveExec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mArchiveExec", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMArchiveExec {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveExec.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveExec.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mArchiveExec/goRequest", output = "http://be.montage.ufc.br/I_mArchiveExec/goResponse")
    public void go();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveExec.SetTblUses")
    @ResponseWrapper(localName = "setTblUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveExec.SetTblUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mArchiveExec/setTblUsesRequest", output = "http://be.montage.ufc.br/I_mArchiveExec/setTblUsesResponse")
    public void setTblUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveExec.SetDirUses")
    @ResponseWrapper(localName = "setDirUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mArchiveExec.SetDirUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mArchiveExec/setDirUsesRequest", output = "http://be.montage.ufc.br/I_mArchiveExec/setDirUsesResponse")
    public void setDirUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
