
package br.montage.stubs.mDiffExec;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_mDiffExecImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10007/mDiffExec?wsdl")
public class IMDiffExecImplService
    extends Service
{

    private final static URL IMDIFFEXECIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMDIFFEXECIMPLSERVICE_EXCEPTION;
    private final static QName IMDIFFEXECIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_mDiffExecImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10007/mDiffExec?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMDIFFEXECIMPLSERVICE_WSDL_LOCATION = url;
        IMDIFFEXECIMPLSERVICE_EXCEPTION = e;
    }

    public IMDiffExecImplService() {
        super(__getWsdlLocation(), IMDIFFEXECIMPLSERVICE_QNAME);
    }

    public IMDiffExecImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMDIFFEXECIMPLSERVICE_QNAME, features);
    }

    public IMDiffExecImplService(URL wsdlLocation) {
        super(wsdlLocation, IMDIFFEXECIMPLSERVICE_QNAME);
    }

    public IMDiffExecImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMDIFFEXECIMPLSERVICE_QNAME, features);
    }

    public IMDiffExecImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMDiffExecImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMDiffExec
     */
    @WebEndpoint(name = "I_mDiffExecImplPort")
    public IMDiffExec getIMDiffExecImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mDiffExecImplPort"), IMDiffExec.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMDiffExec
     */
    @WebEndpoint(name = "I_mDiffExecImplPort")
    public IMDiffExec getIMDiffExecImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mDiffExecImplPort"), IMDiffExec.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMDIFFEXECIMPLSERVICE_EXCEPTION!= null) {
            throw IMDIFFEXECIMPLSERVICE_EXCEPTION;
        }
        return IMDIFFEXECIMPLSERVICE_WSDL_LOCATION;
    }

}
