
package br.montage.stubs.mDiffExec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "I_mDiffExec", targetNamespace = "http://be.montage.ufc.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMDiffExec {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setTblPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetTblPortUses")
    @ResponseWrapper(localName = "setTblPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetTblPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mDiffExec/setTblPortUsesRequest", output = "http://be.montage.ufc.br/I_mDiffExec/setTblPortUsesResponse")
    public void setTblPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setHdrPortUses", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetHdrPortUses")
    @ResponseWrapper(localName = "setHdrPortUsesResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetHdrPortUsesResponse")
    @Action(input = "http://be.montage.ufc.br/I_mDiffExec/setHdrPortUsesRequest", output = "http://be.montage.ufc.br/I_mDiffExec/setHdrPortUsesResponse")
    public void setHdrPortUses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "go", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.Go")
    @ResponseWrapper(localName = "goResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.GoResponse")
    @Action(input = "http://be.montage.ufc.br/I_mDiffExec/goRequest", output = "http://be.montage.ufc.br/I_mDiffExec/goResponse")
    public void go();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUsesOut", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetDirPortUsesOut")
    @ResponseWrapper(localName = "setDirPortUsesOutResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetDirPortUsesOutResponse")
    @Action(input = "http://be.montage.ufc.br/I_mDiffExec/setDirPortUsesOutRequest", output = "http://be.montage.ufc.br/I_mDiffExec/setDirPortUsesOutResponse")
    public void setDirPortUsesOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirPortUsesIn", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetDirPortUsesIn")
    @ResponseWrapper(localName = "setDirPortUsesInResponse", targetNamespace = "http://be.montage.ufc.br/", className = "br.montage.stubs.mDiffExec.SetDirPortUsesInResponse")
    @Action(input = "http://be.montage.ufc.br/I_mDiffExec/setDirPortUsesInRequest", output = "http://be.montage.ufc.br/I_mDiffExec/setDirPortUsesInResponse")
    public void setDirPortUsesIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
