
package br.montage.stubs.mBgModel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "I_mBgModelImplService", targetNamespace = "http://be.montage.ufc.br/", wsdlLocation = "http://localhost:10006/mBgModel?wsdl")
public class IMBgModelImplService
    extends Service
{

    private final static URL IMBGMODELIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMBGMODELIMPLSERVICE_EXCEPTION;
    private final static QName IMBGMODELIMPLSERVICE_QNAME = new QName("http://be.montage.ufc.br/", "I_mBgModelImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10006/mBgModel?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMBGMODELIMPLSERVICE_WSDL_LOCATION = url;
        IMBGMODELIMPLSERVICE_EXCEPTION = e;
    }

    public IMBgModelImplService() {
        super(__getWsdlLocation(), IMBGMODELIMPLSERVICE_QNAME);
    }

    public IMBgModelImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMBGMODELIMPLSERVICE_QNAME, features);
    }

    public IMBgModelImplService(URL wsdlLocation) {
        super(wsdlLocation, IMBGMODELIMPLSERVICE_QNAME);
    }

    public IMBgModelImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMBGMODELIMPLSERVICE_QNAME, features);
    }

    public IMBgModelImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMBgModelImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMBgModel
     */
    @WebEndpoint(name = "I_mBgModelImplPort")
    public IMBgModel getIMBgModelImplPort() {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mBgModelImplPort"), IMBgModel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMBgModel
     */
    @WebEndpoint(name = "I_mBgModelImplPort")
    public IMBgModel getIMBgModelImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://be.montage.ufc.br/", "I_mBgModelImplPort"), IMBgModel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMBGMODELIMPLSERVICE_EXCEPTION!= null) {
            throw IMBGMODELIMPLSERVICE_EXCEPTION;
        }
        return IMBGMODELIMPLSERVICE_WSDL_LOCATION;
    }

}
