
package br.ufc.m101.stubs.mdiffexec.tsk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MDiffExecTskPortImplService", targetNamespace = "http://mdiffexec.component.m101.ufc.br/", wsdlLocation = "http://localhost:11407/mdiffexec-tsk?wsdl")
public class MDiffExecTskPortImplService
    extends Service
{

    private final static URL MDIFFEXECTSKPORTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MDIFFEXECTSKPORTIMPLSERVICE_EXCEPTION;
    private final static QName MDIFFEXECTSKPORTIMPLSERVICE_QNAME = new QName("http://mdiffexec.component.m101.ufc.br/", "MDiffExecTskPortImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11407/mdiffexec-tsk?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDIFFEXECTSKPORTIMPLSERVICE_WSDL_LOCATION = url;
        MDIFFEXECTSKPORTIMPLSERVICE_EXCEPTION = e;
    }

    public MDiffExecTskPortImplService() {
        super(__getWsdlLocation(), MDIFFEXECTSKPORTIMPLSERVICE_QNAME);
    }

    public MDiffExecTskPortImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDIFFEXECTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MDiffExecTskPortImplService(URL wsdlLocation) {
        super(wsdlLocation, MDIFFEXECTSKPORTIMPLSERVICE_QNAME);
    }

    public MDiffExecTskPortImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDIFFEXECTSKPORTIMPLSERVICE_QNAME, features);
    }

    public MDiffExecTskPortImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDiffExecTskPortImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MDiffExecTskPort
     */
    @WebEndpoint(name = "MDiffExecTskPortImplPort")
    public MDiffExecTskPort getMDiffExecTskPortImplPort() {
        return super.getPort(new QName("http://mdiffexec.component.m101.ufc.br/", "MDiffExecTskPortImplPort"), MDiffExecTskPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDiffExecTskPort
     */
    @WebEndpoint(name = "MDiffExecTskPortImplPort")
    public MDiffExecTskPort getMDiffExecTskPortImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdiffexec.component.m101.ufc.br/", "MDiffExecTskPortImplPort"), MDiffExecTskPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDIFFEXECTSKPORTIMPLSERVICE_EXCEPTION!= null) {
            throw MDIFFEXECTSKPORTIMPLSERVICE_EXCEPTION;
        }
        return MDIFFEXECTSKPORTIMPLSERVICE_WSDL_LOCATION;
    }

}
